// Code generated by protoc-gen-go.
// source: acl.proto
// DO NOT EDIT!

package hadoop_hdfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AclEntryProto_AclEntryScopeProto int32

const (
	AclEntryProto_ACCESS  AclEntryProto_AclEntryScopeProto = 0
	AclEntryProto_DEFAULT AclEntryProto_AclEntryScopeProto = 1
)

var AclEntryProto_AclEntryScopeProto_name = map[int32]string{
	0: "ACCESS",
	1: "DEFAULT",
}
var AclEntryProto_AclEntryScopeProto_value = map[string]int32{
	"ACCESS":  0,
	"DEFAULT": 1,
}

func (x AclEntryProto_AclEntryScopeProto) Enum() *AclEntryProto_AclEntryScopeProto {
	p := new(AclEntryProto_AclEntryScopeProto)
	*p = x
	return p
}
func (x AclEntryProto_AclEntryScopeProto) String() string {
	return proto.EnumName(AclEntryProto_AclEntryScopeProto_name, int32(x))
}
func (x *AclEntryProto_AclEntryScopeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AclEntryProto_AclEntryScopeProto_value, data, "AclEntryProto_AclEntryScopeProto")
	if err != nil {
		return err
	}
	*x = AclEntryProto_AclEntryScopeProto(value)
	return nil
}
func (AclEntryProto_AclEntryScopeProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0}
}

type AclEntryProto_AclEntryTypeProto int32

const (
	AclEntryProto_USER  AclEntryProto_AclEntryTypeProto = 0
	AclEntryProto_GROUP AclEntryProto_AclEntryTypeProto = 1
	AclEntryProto_MASK  AclEntryProto_AclEntryTypeProto = 2
	AclEntryProto_OTHER AclEntryProto_AclEntryTypeProto = 3
)

var AclEntryProto_AclEntryTypeProto_name = map[int32]string{
	0: "USER",
	1: "GROUP",
	2: "MASK",
	3: "OTHER",
}
var AclEntryProto_AclEntryTypeProto_value = map[string]int32{
	"USER":  0,
	"GROUP": 1,
	"MASK":  2,
	"OTHER": 3,
}

func (x AclEntryProto_AclEntryTypeProto) Enum() *AclEntryProto_AclEntryTypeProto {
	p := new(AclEntryProto_AclEntryTypeProto)
	*p = x
	return p
}
func (x AclEntryProto_AclEntryTypeProto) String() string {
	return proto.EnumName(AclEntryProto_AclEntryTypeProto_name, int32(x))
}
func (x *AclEntryProto_AclEntryTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AclEntryProto_AclEntryTypeProto_value, data, "AclEntryProto_AclEntryTypeProto")
	if err != nil {
		return err
	}
	*x = AclEntryProto_AclEntryTypeProto(value)
	return nil
}
func (AclEntryProto_AclEntryTypeProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 1}
}

type AclEntryProto_FsActionProto int32

const (
	AclEntryProto_NONE          AclEntryProto_FsActionProto = 0
	AclEntryProto_EXECUTE       AclEntryProto_FsActionProto = 1
	AclEntryProto_WRITE         AclEntryProto_FsActionProto = 2
	AclEntryProto_WRITE_EXECUTE AclEntryProto_FsActionProto = 3
	AclEntryProto_READ          AclEntryProto_FsActionProto = 4
	AclEntryProto_READ_EXECUTE  AclEntryProto_FsActionProto = 5
	AclEntryProto_READ_WRITE    AclEntryProto_FsActionProto = 6
	AclEntryProto_PERM_ALL      AclEntryProto_FsActionProto = 7
)

var AclEntryProto_FsActionProto_name = map[int32]string{
	0: "NONE",
	1: "EXECUTE",
	2: "WRITE",
	3: "WRITE_EXECUTE",
	4: "READ",
	5: "READ_EXECUTE",
	6: "READ_WRITE",
	7: "PERM_ALL",
}
var AclEntryProto_FsActionProto_value = map[string]int32{
	"NONE":          0,
	"EXECUTE":       1,
	"WRITE":         2,
	"WRITE_EXECUTE": 3,
	"READ":          4,
	"READ_EXECUTE":  5,
	"READ_WRITE":    6,
	"PERM_ALL":      7,
}

func (x AclEntryProto_FsActionProto) Enum() *AclEntryProto_FsActionProto {
	p := new(AclEntryProto_FsActionProto)
	*p = x
	return p
}
func (x AclEntryProto_FsActionProto) String() string {
	return proto.EnumName(AclEntryProto_FsActionProto_name, int32(x))
}
func (x *AclEntryProto_FsActionProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AclEntryProto_FsActionProto_value, data, "AclEntryProto_FsActionProto")
	if err != nil {
		return err
	}
	*x = AclEntryProto_FsActionProto(value)
	return nil
}
func (AclEntryProto_FsActionProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 2}
}

type AclEntryProto struct {
	Type             *AclEntryProto_AclEntryTypeProto  `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.AclEntryProto_AclEntryTypeProto" json:"type,omitempty"`
	Scope            *AclEntryProto_AclEntryScopeProto `protobuf:"varint,2,req,name=scope,enum=hadoop.hdfs.AclEntryProto_AclEntryScopeProto" json:"scope,omitempty"`
	Permissions      *AclEntryProto_FsActionProto      `protobuf:"varint,3,req,name=permissions,enum=hadoop.hdfs.AclEntryProto_FsActionProto" json:"permissions,omitempty"`
	Name             *string                           `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *AclEntryProto) Reset()                    { *m = AclEntryProto{} }
func (m *AclEntryProto) String() string            { return proto.CompactTextString(m) }
func (*AclEntryProto) ProtoMessage()               {}
func (*AclEntryProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *AclEntryProto) GetType() AclEntryProto_AclEntryTypeProto {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return AclEntryProto_USER
}

func (m *AclEntryProto) GetScope() AclEntryProto_AclEntryScopeProto {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return AclEntryProto_ACCESS
}

func (m *AclEntryProto) GetPermissions() AclEntryProto_FsActionProto {
	if m != nil && m.Permissions != nil {
		return *m.Permissions
	}
	return AclEntryProto_NONE
}

func (m *AclEntryProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type AclStatusProto struct {
	Owner            *string            `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Group            *string            `protobuf:"bytes,2,req,name=group" json:"group,omitempty"`
	Sticky           *bool              `protobuf:"varint,3,req,name=sticky" json:"sticky,omitempty"`
	Entries          []*AclEntryProto   `protobuf:"bytes,4,rep,name=entries" json:"entries,omitempty"`
	Permission       *FsPermissionProto `protobuf:"bytes,5,opt,name=permission" json:"permission,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AclStatusProto) Reset()                    { *m = AclStatusProto{} }
func (m *AclStatusProto) String() string            { return proto.CompactTextString(m) }
func (*AclStatusProto) ProtoMessage()               {}
func (*AclStatusProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *AclStatusProto) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *AclStatusProto) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *AclStatusProto) GetSticky() bool {
	if m != nil && m.Sticky != nil {
		return *m.Sticky
	}
	return false
}

func (m *AclStatusProto) GetEntries() []*AclEntryProto {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AclStatusProto) GetPermission() *FsPermissionProto {
	if m != nil {
		return m.Permission
	}
	return nil
}

type AclEditLogProto struct {
	Src              *string          `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Entries          []*AclEntryProto `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AclEditLogProto) Reset()                    { *m = AclEditLogProto{} }
func (m *AclEditLogProto) String() string            { return proto.CompactTextString(m) }
func (*AclEditLogProto) ProtoMessage()               {}
func (*AclEditLogProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *AclEditLogProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *AclEditLogProto) GetEntries() []*AclEntryProto {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ModifyAclEntriesRequestProto struct {
	Src              *string          `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	AclSpec          []*AclEntryProto `protobuf:"bytes,2,rep,name=aclSpec" json:"aclSpec,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ModifyAclEntriesRequestProto) Reset()                    { *m = ModifyAclEntriesRequestProto{} }
func (m *ModifyAclEntriesRequestProto) String() string            { return proto.CompactTextString(m) }
func (*ModifyAclEntriesRequestProto) ProtoMessage()               {}
func (*ModifyAclEntriesRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *ModifyAclEntriesRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *ModifyAclEntriesRequestProto) GetAclSpec() []*AclEntryProto {
	if m != nil {
		return m.AclSpec
	}
	return nil
}

type ModifyAclEntriesResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ModifyAclEntriesResponseProto) Reset()                    { *m = ModifyAclEntriesResponseProto{} }
func (m *ModifyAclEntriesResponseProto) String() string            { return proto.CompactTextString(m) }
func (*ModifyAclEntriesResponseProto) ProtoMessage()               {}
func (*ModifyAclEntriesResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

type RemoveAclRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoveAclRequestProto) Reset()                    { *m = RemoveAclRequestProto{} }
func (m *RemoveAclRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveAclRequestProto) ProtoMessage()               {}
func (*RemoveAclRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *RemoveAclRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type RemoveAclResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveAclResponseProto) Reset()                    { *m = RemoveAclResponseProto{} }
func (m *RemoveAclResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveAclResponseProto) ProtoMessage()               {}
func (*RemoveAclResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

type RemoveAclEntriesRequestProto struct {
	Src              *string          `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	AclSpec          []*AclEntryProto `protobuf:"bytes,2,rep,name=aclSpec" json:"aclSpec,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RemoveAclEntriesRequestProto) Reset()                    { *m = RemoveAclEntriesRequestProto{} }
func (m *RemoveAclEntriesRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveAclEntriesRequestProto) ProtoMessage()               {}
func (*RemoveAclEntriesRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *RemoveAclEntriesRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *RemoveAclEntriesRequestProto) GetAclSpec() []*AclEntryProto {
	if m != nil {
		return m.AclSpec
	}
	return nil
}

type RemoveAclEntriesResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveAclEntriesResponseProto) Reset()                    { *m = RemoveAclEntriesResponseProto{} }
func (m *RemoveAclEntriesResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveAclEntriesResponseProto) ProtoMessage()               {}
func (*RemoveAclEntriesResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

type RemoveDefaultAclRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoveDefaultAclRequestProto) Reset()                    { *m = RemoveDefaultAclRequestProto{} }
func (m *RemoveDefaultAclRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveDefaultAclRequestProto) ProtoMessage()               {}
func (*RemoveDefaultAclRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *RemoveDefaultAclRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type RemoveDefaultAclResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveDefaultAclResponseProto) Reset()                    { *m = RemoveDefaultAclResponseProto{} }
func (m *RemoveDefaultAclResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveDefaultAclResponseProto) ProtoMessage()               {}
func (*RemoveDefaultAclResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

type SetAclRequestProto struct {
	Src              *string          `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	AclSpec          []*AclEntryProto `protobuf:"bytes,2,rep,name=aclSpec" json:"aclSpec,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SetAclRequestProto) Reset()                    { *m = SetAclRequestProto{} }
func (m *SetAclRequestProto) String() string            { return proto.CompactTextString(m) }
func (*SetAclRequestProto) ProtoMessage()               {}
func (*SetAclRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *SetAclRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetAclRequestProto) GetAclSpec() []*AclEntryProto {
	if m != nil {
		return m.AclSpec
	}
	return nil
}

type SetAclResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetAclResponseProto) Reset()                    { *m = SetAclResponseProto{} }
func (m *SetAclResponseProto) String() string            { return proto.CompactTextString(m) }
func (*SetAclResponseProto) ProtoMessage()               {}
func (*SetAclResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

type GetAclStatusRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAclStatusRequestProto) Reset()                    { *m = GetAclStatusRequestProto{} }
func (m *GetAclStatusRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetAclStatusRequestProto) ProtoMessage()               {}
func (*GetAclStatusRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *GetAclStatusRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type GetAclStatusResponseProto struct {
	Result           *AclStatusProto `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetAclStatusResponseProto) Reset()                    { *m = GetAclStatusResponseProto{} }
func (m *GetAclStatusResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetAclStatusResponseProto) ProtoMessage()               {}
func (*GetAclStatusResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *GetAclStatusResponseProto) GetResult() *AclStatusProto {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*AclEntryProto)(nil), "hadoop.hdfs.AclEntryProto")
	proto.RegisterType((*AclStatusProto)(nil), "hadoop.hdfs.AclStatusProto")
	proto.RegisterType((*AclEditLogProto)(nil), "hadoop.hdfs.AclEditLogProto")
	proto.RegisterType((*ModifyAclEntriesRequestProto)(nil), "hadoop.hdfs.ModifyAclEntriesRequestProto")
	proto.RegisterType((*ModifyAclEntriesResponseProto)(nil), "hadoop.hdfs.ModifyAclEntriesResponseProto")
	proto.RegisterType((*RemoveAclRequestProto)(nil), "hadoop.hdfs.RemoveAclRequestProto")
	proto.RegisterType((*RemoveAclResponseProto)(nil), "hadoop.hdfs.RemoveAclResponseProto")
	proto.RegisterType((*RemoveAclEntriesRequestProto)(nil), "hadoop.hdfs.RemoveAclEntriesRequestProto")
	proto.RegisterType((*RemoveAclEntriesResponseProto)(nil), "hadoop.hdfs.RemoveAclEntriesResponseProto")
	proto.RegisterType((*RemoveDefaultAclRequestProto)(nil), "hadoop.hdfs.RemoveDefaultAclRequestProto")
	proto.RegisterType((*RemoveDefaultAclResponseProto)(nil), "hadoop.hdfs.RemoveDefaultAclResponseProto")
	proto.RegisterType((*SetAclRequestProto)(nil), "hadoop.hdfs.SetAclRequestProto")
	proto.RegisterType((*SetAclResponseProto)(nil), "hadoop.hdfs.SetAclResponseProto")
	proto.RegisterType((*GetAclStatusRequestProto)(nil), "hadoop.hdfs.GetAclStatusRequestProto")
	proto.RegisterType((*GetAclStatusResponseProto)(nil), "hadoop.hdfs.GetAclStatusResponseProto")
	proto.RegisterEnum("hadoop.hdfs.AclEntryProto_AclEntryScopeProto", AclEntryProto_AclEntryScopeProto_name, AclEntryProto_AclEntryScopeProto_value)
	proto.RegisterEnum("hadoop.hdfs.AclEntryProto_AclEntryTypeProto", AclEntryProto_AclEntryTypeProto_name, AclEntryProto_AclEntryTypeProto_value)
	proto.RegisterEnum("hadoop.hdfs.AclEntryProto_FsActionProto", AclEntryProto_FsActionProto_name, AclEntryProto_FsActionProto_value)
}

var fileDescriptor3 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x4b, 0x6f, 0xda, 0x5c,
	0x10, 0xfd, 0x8c, 0x79, 0x79, 0x1c, 0xf8, 0x1c, 0x57, 0xa9, 0xdc, 0xf4, 0x15, 0x59, 0xad, 0x8a,
	0x94, 0x86, 0x05, 0x52, 0x37, 0x55, 0xb3, 0x70, 0xc0, 0x24, 0x55, 0x78, 0xc9, 0x06, 0x35, 0xbb,
	0xc8, 0x32, 0x17, 0xb0, 0x0a, 0x5c, 0xd7, 0xd7, 0xb4, 0x62, 0xd3, 0xbf, 0xd2, 0xfe, 0x98, 0xfe,
	0xb0, 0x8e, 0xaf, 0x81, 0xda, 0x25, 0xd0, 0x54, 0xea, 0xc6, 0xba, 0x9e, 0x39, 0xe7, 0xcc, 0x99,
	0xb9, 0x0f, 0x90, 0x1c, 0x77, 0x5a, 0xf5, 0x03, 0x1a, 0x52, 0x55, 0x9e, 0x38, 0x43, 0x4a, 0xfd,
	0xea, 0x64, 0x38, 0x62, 0xc7, 0x10, 0x7d, 0xe3, 0x84, 0xfe, 0x43, 0x84, 0x92, 0xe1, 0x4e, 0xcd,
	0x79, 0x18, 0x2c, 0x7b, 0x1c, 0xfa, 0x16, 0xb2, 0xe1, 0xd2, 0x27, 0x9a, 0x70, 0x92, 0xa9, 0x94,
	0x6b, 0xaf, 0xab, 0x09, 0x66, 0x35, 0x85, 0xdc, 0xfc, 0xf5, 0x11, 0x1e, 0x73, 0xdf, 0x41, 0x8e,
	0xb9, 0x14, 0xc9, 0x19, 0x4e, 0x3e, 0xbb, 0x07, 0xd9, 0x8e, 0xf0, 0x31, 0xfb, 0x1c, 0x64, 0x9f,
	0x04, 0x33, 0x8f, 0x31, 0x8f, 0xce, 0x99, 0x26, 0x72, 0x8d, 0xca, 0x1e, 0x8d, 0x26, 0x33, 0xdc,
	0x10, 0xb1, 0x31, 0xfd, 0x00, 0xb2, 0x73, 0x67, 0x46, 0xb4, 0xec, 0x89, 0x50, 0x91, 0xf4, 0x33,
	0x50, 0xef, 0x28, 0x01, 0x90, 0x37, 0xea, 0x75, 0xd3, 0xb6, 0x95, 0xff, 0x54, 0x19, 0x0a, 0x0d,
	0xb3, 0x69, 0x0c, 0x5a, 0x7d, 0x45, 0xd0, 0xcf, 0xe1, 0x70, 0xbb, 0x9d, 0x22, 0x64, 0x07, 0xb6,
	0x69, 0x21, 0x56, 0x82, 0xdc, 0xa5, 0xd5, 0x1d, 0xf4, 0x14, 0x21, 0x0a, 0xb6, 0x0d, 0xfb, 0x5a,
	0xc9, 0x44, 0xc1, 0x6e, 0xff, 0x0a, 0xf3, 0xa2, 0xfe, 0x15, 0x4a, 0x69, 0x33, 0x88, 0xea, 0x74,
	0x3b, 0x66, 0x5c, 0xc6, 0xbc, 0x31, 0xeb, 0x83, 0xbe, 0x89, 0x64, 0xa4, 0x7c, 0xb0, 0xde, 0xe3,
	0x32, 0xa3, 0x1e, 0x42, 0x89, 0x2f, 0x6f, 0xd7, 0x59, 0x31, 0x22, 0x59, 0xa6, 0xd1, 0x50, 0xb2,
	0xaa, 0x02, 0x07, 0xd1, 0x6a, 0x93, 0xcb, 0xa9, 0x65, 0x00, 0x1e, 0x89, 0xe9, 0x79, 0xec, 0xb6,
	0xd8, 0x33, 0xad, 0xf6, 0xad, 0xd1, 0x6a, 0x29, 0x05, 0xfd, 0x9b, 0x00, 0x65, 0xf4, 0x6f, 0x87,
	0x4e, 0xb8, 0x60, 0xb1, 0x83, 0x12, 0xe4, 0xe8, 0x97, 0x39, 0x09, 0xf8, 0x46, 0x4a, 0xd1, 0xef,
	0x38, 0xa0, 0x0b, 0x9f, 0x6f, 0x8d, 0x84, 0x72, 0x79, 0x16, 0x7a, 0xee, 0xc7, 0x25, 0x1f, 0x73,
	0x51, 0x3d, 0x85, 0x02, 0xc1, 0xe6, 0x3d, 0xc2, 0x70, 0x7e, 0x62, 0x45, 0xae, 0x1d, 0xef, 0x9e,
	0xbb, 0x5a, 0x03, 0xf8, 0xb5, 0x51, 0x5a, 0x0e, 0xe7, 0x2d, 0xd7, 0x9e, 0xa5, 0xf0, 0x4d, 0xd6,
	0xdb, 0x00, 0x38, 0x47, 0xbf, 0x86, 0xff, 0x23, 0x91, 0xa1, 0x17, 0xb6, 0xe8, 0x38, 0x96, 0x91,
	0x41, 0x64, 0x81, 0xbb, 0xf2, 0x97, 0x30, 0x90, 0xf9, 0x93, 0x01, 0xfd, 0x06, 0x9e, 0xb4, 0xe9,
	0xd0, 0x1b, 0x2d, 0x57, 0x61, 0x64, 0x59, 0xe4, 0xd3, 0x82, 0xb0, 0xf0, 0x6e, 0x65, 0xbc, 0x08,
	0xb6, 0x4f, 0xdc, 0x7b, 0x28, 0x3f, 0x87, 0xa7, 0xdb, 0xca, 0xcc, 0xc7, 0xf3, 0x18, 0x9f, 0x09,
	0xfd, 0x05, 0x1c, 0x59, 0x64, 0x46, 0x3f, 0x13, 0x04, 0xec, 0xac, 0xa9, 0x6b, 0xf0, 0x30, 0x81,
	0x4a, 0xf2, 0xd1, 0xfa, 0x26, 0xf3, 0xcf, 0xad, 0x6f, 0x2b, 0x27, 0x4b, 0x9f, 0xae, 0x4b, 0x37,
	0xc8, 0xc8, 0x59, 0x4c, 0xc3, 0xbd, 0x1d, 0x6c, 0xd4, 0x92, 0xe0, 0xa4, 0x5a, 0x07, 0x54, 0x9b,
	0xec, 0xd5, 0xf8, 0x3b, 0xfb, 0x47, 0xf0, 0x60, 0xad, 0x97, 0x2c, 0xf3, 0x0a, 0xb4, 0x4b, 0x1e,
	0x8e, 0xcf, 0xf6, 0x6e, 0xc3, 0x57, 0xf0, 0x28, 0x0d, 0x4c, 0xa8, 0xa0, 0x93, 0x7c, 0x40, 0x18,
	0xb6, 0xc1, 0xc1, 0x72, 0xed, 0xf1, 0xef, 0x46, 0x12, 0x37, 0xe7, 0xe2, 0x0d, 0xbc, 0xa4, 0xc1,
	0xb8, 0xea, 0xf8, 0x8e, 0x3b, 0x21, 0x29, 0x20, 0x7f, 0x33, 0x5d, 0xba, 0x7a, 0x55, 0x2f, 0x24,
	0x24, 0x72, 0x0a, 0xfb, 0x2e, 0x08, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x0a, 0xa6, 0x5b,
	0x6f, 0x05, 0x00, 0x00,
}
