// Code generated by protoc-gen-go.
// source: ClientNamenodeProtocol.proto
// DO NOT EDIT!

/*
Package hadoop_hdfs is a generated protocol buffer package.

It is generated from these files:
	ClientNamenodeProtocol.proto
	datatransfer.proto
	hdfs.proto

It has these top-level messages:
	GetBlockLocationsRequestProto
	GetBlockLocationsResponseProto
	GetServerDefaultsRequestProto
	GetServerDefaultsResponseProto
	CreateRequestProto
	CreateResponseProto
	AppendRequestProto
	AppendResponseProto
	SetReplicationRequestProto
	SetReplicationResponseProto
	SetPermissionRequestProto
	SetPermissionResponseProto
	SetOwnerRequestProto
	SetOwnerResponseProto
	AbandonBlockRequestProto
	AbandonBlockResponseProto
	AddBlockRequestProto
	AddBlockResponseProto
	GetAdditionalDatanodeRequestProto
	GetAdditionalDatanodeResponseProto
	CompleteRequestProto
	CompleteResponseProto
	ReportBadBlocksRequestProto
	ReportBadBlocksResponseProto
	ConcatRequestProto
	ConcatResponseProto
	RenameRequestProto
	RenameResponseProto
	Rename2RequestProto
	Rename2ResponseProto
	DeleteRequestProto
	DeleteResponseProto
	MkdirsRequestProto
	MkdirsResponseProto
	GetListingRequestProto
	GetListingResponseProto
	GetSnapshottableDirListingRequestProto
	GetSnapshottableDirListingResponseProto
	GetSnapshotDiffReportRequestProto
	GetSnapshotDiffReportResponseProto
	RenewLeaseRequestProto
	RenewLeaseResponseProto
	RecoverLeaseRequestProto
	RecoverLeaseResponseProto
	GetFsStatusRequestProto
	GetFsStatsResponseProto
	GetDatanodeReportRequestProto
	GetDatanodeReportResponseProto
	GetPreferredBlockSizeRequestProto
	GetPreferredBlockSizeResponseProto
	SetSafeModeRequestProto
	SetSafeModeResponseProto
	SaveNamespaceRequestProto
	SaveNamespaceResponseProto
	RollEditsRequestProto
	RollEditsResponseProto
	RestoreFailedStorageRequestProto
	RestoreFailedStorageResponseProto
	RefreshNodesRequestProto
	RefreshNodesResponseProto
	FinalizeUpgradeRequestProto
	FinalizeUpgradeResponseProto
	ListCorruptFileBlocksRequestProto
	ListCorruptFileBlocksResponseProto
	MetaSaveRequestProto
	MetaSaveResponseProto
	GetFileInfoRequestProto
	GetFileInfoResponseProto
	IsFileClosedRequestProto
	IsFileClosedResponseProto
	GetFileLinkInfoRequestProto
	GetFileLinkInfoResponseProto
	GetContentSummaryRequestProto
	GetContentSummaryResponseProto
	SetQuotaRequestProto
	SetQuotaResponseProto
	FsyncRequestProto
	FsyncResponseProto
	SetTimesRequestProto
	SetTimesResponseProto
	CreateSymlinkRequestProto
	CreateSymlinkResponseProto
	GetLinkTargetRequestProto
	GetLinkTargetResponseProto
	UpdateBlockForPipelineRequestProto
	UpdateBlockForPipelineResponseProto
	UpdatePipelineRequestProto
	UpdatePipelineResponseProto
	SetBalancerBandwidthRequestProto
	SetBalancerBandwidthResponseProto
	GetDataEncryptionKeyRequestProto
	GetDataEncryptionKeyResponseProto
	CreateSnapshotRequestProto
	CreateSnapshotResponseProto
	RenameSnapshotRequestProto
	RenameSnapshotResponseProto
	AllowSnapshotRequestProto
	AllowSnapshotResponseProto
	DisallowSnapshotRequestProto
	DisallowSnapshotResponseProto
	DeleteSnapshotRequestProto
	DeleteSnapshotResponseProto
*/
package hadoop_hdfs

import proto "github.com/golang/protobuf/proto"
import math "math"

// discarding unused import hadoop_common "Security.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CreateFlagProto int32

const (
	CreateFlagProto_CREATE    CreateFlagProto = 1
	CreateFlagProto_OVERWRITE CreateFlagProto = 2
	CreateFlagProto_APPEND    CreateFlagProto = 4
)

var CreateFlagProto_name = map[int32]string{
	1: "CREATE",
	2: "OVERWRITE",
	4: "APPEND",
}
var CreateFlagProto_value = map[string]int32{
	"CREATE":    1,
	"OVERWRITE": 2,
	"APPEND":    4,
}

func (x CreateFlagProto) Enum() *CreateFlagProto {
	p := new(CreateFlagProto)
	*p = x
	return p
}
func (x CreateFlagProto) String() string {
	return proto.EnumName(CreateFlagProto_name, int32(x))
}
func (x *CreateFlagProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CreateFlagProto_value, data, "CreateFlagProto")
	if err != nil {
		return err
	}
	*x = CreateFlagProto(value)
	return nil
}

type DatanodeReportTypeProto int32

const (
	DatanodeReportTypeProto_ALL  DatanodeReportTypeProto = 1
	DatanodeReportTypeProto_LIVE DatanodeReportTypeProto = 2
	DatanodeReportTypeProto_DEAD DatanodeReportTypeProto = 3
)

var DatanodeReportTypeProto_name = map[int32]string{
	1: "ALL",
	2: "LIVE",
	3: "DEAD",
}
var DatanodeReportTypeProto_value = map[string]int32{
	"ALL":  1,
	"LIVE": 2,
	"DEAD": 3,
}

func (x DatanodeReportTypeProto) Enum() *DatanodeReportTypeProto {
	p := new(DatanodeReportTypeProto)
	*p = x
	return p
}
func (x DatanodeReportTypeProto) String() string {
	return proto.EnumName(DatanodeReportTypeProto_name, int32(x))
}
func (x *DatanodeReportTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DatanodeReportTypeProto_value, data, "DatanodeReportTypeProto")
	if err != nil {
		return err
	}
	*x = DatanodeReportTypeProto(value)
	return nil
}

type SafeModeActionProto int32

const (
	SafeModeActionProto_SAFEMODE_LEAVE SafeModeActionProto = 1
	SafeModeActionProto_SAFEMODE_ENTER SafeModeActionProto = 2
	SafeModeActionProto_SAFEMODE_GET   SafeModeActionProto = 3
)

var SafeModeActionProto_name = map[int32]string{
	1: "SAFEMODE_LEAVE",
	2: "SAFEMODE_ENTER",
	3: "SAFEMODE_GET",
}
var SafeModeActionProto_value = map[string]int32{
	"SAFEMODE_LEAVE": 1,
	"SAFEMODE_ENTER": 2,
	"SAFEMODE_GET":   3,
}

func (x SafeModeActionProto) Enum() *SafeModeActionProto {
	p := new(SafeModeActionProto)
	*p = x
	return p
}
func (x SafeModeActionProto) String() string {
	return proto.EnumName(SafeModeActionProto_name, int32(x))
}
func (x *SafeModeActionProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SafeModeActionProto_value, data, "SafeModeActionProto")
	if err != nil {
		return err
	}
	*x = SafeModeActionProto(value)
	return nil
}

type GetBlockLocationsRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Offset           *uint64 `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	Length           *uint64 `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetBlockLocationsRequestProto) Reset()         { *m = GetBlockLocationsRequestProto{} }
func (m *GetBlockLocationsRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetBlockLocationsRequestProto) ProtoMessage()    {}

func (m *GetBlockLocationsRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *GetBlockLocationsRequestProto) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *GetBlockLocationsRequestProto) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type GetBlockLocationsResponseProto struct {
	Locations        *LocatedBlocksProto `protobuf:"bytes,1,opt,name=locations" json:"locations,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetBlockLocationsResponseProto) Reset()         { *m = GetBlockLocationsResponseProto{} }
func (m *GetBlockLocationsResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetBlockLocationsResponseProto) ProtoMessage()    {}

func (m *GetBlockLocationsResponseProto) GetLocations() *LocatedBlocksProto {
	if m != nil {
		return m.Locations
	}
	return nil
}

type GetServerDefaultsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetServerDefaultsRequestProto) Reset()         { *m = GetServerDefaultsRequestProto{} }
func (m *GetServerDefaultsRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetServerDefaultsRequestProto) ProtoMessage()    {}

type GetServerDefaultsResponseProto struct {
	ServerDefaults   *FsServerDefaultsProto `protobuf:"bytes,1,req,name=serverDefaults" json:"serverDefaults,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *GetServerDefaultsResponseProto) Reset()         { *m = GetServerDefaultsResponseProto{} }
func (m *GetServerDefaultsResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetServerDefaultsResponseProto) ProtoMessage()    {}

func (m *GetServerDefaultsResponseProto) GetServerDefaults() *FsServerDefaultsProto {
	if m != nil {
		return m.ServerDefaults
	}
	return nil
}

type CreateRequestProto struct {
	Src              *string            `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Masked           *FsPermissionProto `protobuf:"bytes,2,req,name=masked" json:"masked,omitempty"`
	ClientName       *string            `protobuf:"bytes,3,req,name=clientName" json:"clientName,omitempty"`
	CreateFlag       *uint32            `protobuf:"varint,4,req,name=createFlag" json:"createFlag,omitempty"`
	CreateParent     *bool              `protobuf:"varint,5,req,name=createParent" json:"createParent,omitempty"`
	Replication      *uint32            `protobuf:"varint,6,req,name=replication" json:"replication,omitempty"`
	BlockSize        *uint64            `protobuf:"varint,7,req,name=blockSize" json:"blockSize,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *CreateRequestProto) Reset()         { *m = CreateRequestProto{} }
func (m *CreateRequestProto) String() string { return proto.CompactTextString(m) }
func (*CreateRequestProto) ProtoMessage()    {}

func (m *CreateRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *CreateRequestProto) GetMasked() *FsPermissionProto {
	if m != nil {
		return m.Masked
	}
	return nil
}

func (m *CreateRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *CreateRequestProto) GetCreateFlag() uint32 {
	if m != nil && m.CreateFlag != nil {
		return *m.CreateFlag
	}
	return 0
}

func (m *CreateRequestProto) GetCreateParent() bool {
	if m != nil && m.CreateParent != nil {
		return *m.CreateParent
	}
	return false
}

func (m *CreateRequestProto) GetReplication() uint32 {
	if m != nil && m.Replication != nil {
		return *m.Replication
	}
	return 0
}

func (m *CreateRequestProto) GetBlockSize() uint64 {
	if m != nil && m.BlockSize != nil {
		return *m.BlockSize
	}
	return 0
}

type CreateResponseProto struct {
	Fs               *HdfsFileStatusProto `protobuf:"bytes,1,opt,name=fs" json:"fs,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CreateResponseProto) Reset()         { *m = CreateResponseProto{} }
func (m *CreateResponseProto) String() string { return proto.CompactTextString(m) }
func (*CreateResponseProto) ProtoMessage()    {}

func (m *CreateResponseProto) GetFs() *HdfsFileStatusProto {
	if m != nil {
		return m.Fs
	}
	return nil
}

type AppendRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	ClientName       *string `protobuf:"bytes,2,req,name=clientName" json:"clientName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppendRequestProto) Reset()         { *m = AppendRequestProto{} }
func (m *AppendRequestProto) String() string { return proto.CompactTextString(m) }
func (*AppendRequestProto) ProtoMessage()    {}

func (m *AppendRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *AppendRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

type AppendResponseProto struct {
	Block            *LocatedBlockProto `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AppendResponseProto) Reset()         { *m = AppendResponseProto{} }
func (m *AppendResponseProto) String() string { return proto.CompactTextString(m) }
func (*AppendResponseProto) ProtoMessage()    {}

func (m *AppendResponseProto) GetBlock() *LocatedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

type SetReplicationRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Replication      *uint32 `protobuf:"varint,2,req,name=replication" json:"replication,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetReplicationRequestProto) Reset()         { *m = SetReplicationRequestProto{} }
func (m *SetReplicationRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetReplicationRequestProto) ProtoMessage()    {}

func (m *SetReplicationRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetReplicationRequestProto) GetReplication() uint32 {
	if m != nil && m.Replication != nil {
		return *m.Replication
	}
	return 0
}

type SetReplicationResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetReplicationResponseProto) Reset()         { *m = SetReplicationResponseProto{} }
func (m *SetReplicationResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetReplicationResponseProto) ProtoMessage()    {}

func (m *SetReplicationResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type SetPermissionRequestProto struct {
	Src              *string            `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Permission       *FsPermissionProto `protobuf:"bytes,2,req,name=permission" json:"permission,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SetPermissionRequestProto) Reset()         { *m = SetPermissionRequestProto{} }
func (m *SetPermissionRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetPermissionRequestProto) ProtoMessage()    {}

func (m *SetPermissionRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetPermissionRequestProto) GetPermission() *FsPermissionProto {
	if m != nil {
		return m.Permission
	}
	return nil
}

type SetPermissionResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetPermissionResponseProto) Reset()         { *m = SetPermissionResponseProto{} }
func (m *SetPermissionResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetPermissionResponseProto) ProtoMessage()    {}

type SetOwnerRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Username         *string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Groupname        *string `protobuf:"bytes,3,opt,name=groupname" json:"groupname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetOwnerRequestProto) Reset()         { *m = SetOwnerRequestProto{} }
func (m *SetOwnerRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetOwnerRequestProto) ProtoMessage()    {}

func (m *SetOwnerRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetOwnerRequestProto) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *SetOwnerRequestProto) GetGroupname() string {
	if m != nil && m.Groupname != nil {
		return *m.Groupname
	}
	return ""
}

type SetOwnerResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetOwnerResponseProto) Reset()         { *m = SetOwnerResponseProto{} }
func (m *SetOwnerResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetOwnerResponseProto) ProtoMessage()    {}

type AbandonBlockRequestProto struct {
	B                *ExtendedBlockProto `protobuf:"bytes,1,req,name=b" json:"b,omitempty"`
	Src              *string             `protobuf:"bytes,2,req,name=src" json:"src,omitempty"`
	Holder           *string             `protobuf:"bytes,3,req,name=holder" json:"holder,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *AbandonBlockRequestProto) Reset()         { *m = AbandonBlockRequestProto{} }
func (m *AbandonBlockRequestProto) String() string { return proto.CompactTextString(m) }
func (*AbandonBlockRequestProto) ProtoMessage()    {}

func (m *AbandonBlockRequestProto) GetB() *ExtendedBlockProto {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *AbandonBlockRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *AbandonBlockRequestProto) GetHolder() string {
	if m != nil && m.Holder != nil {
		return *m.Holder
	}
	return ""
}

type AbandonBlockResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AbandonBlockResponseProto) Reset()         { *m = AbandonBlockResponseProto{} }
func (m *AbandonBlockResponseProto) String() string { return proto.CompactTextString(m) }
func (*AbandonBlockResponseProto) ProtoMessage()    {}

type AddBlockRequestProto struct {
	Src              *string              `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	ClientName       *string              `protobuf:"bytes,2,req,name=clientName" json:"clientName,omitempty"`
	Previous         *ExtendedBlockProto  `protobuf:"bytes,3,opt,name=previous" json:"previous,omitempty"`
	ExcludeNodes     []*DatanodeInfoProto `protobuf:"bytes,4,rep,name=excludeNodes" json:"excludeNodes,omitempty"`
	FileId           *uint64              `protobuf:"varint,5,opt,name=fileId,def=0" json:"fileId,omitempty"`
	FavoredNodes     []string             `protobuf:"bytes,6,rep,name=favoredNodes" json:"favoredNodes,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AddBlockRequestProto) Reset()         { *m = AddBlockRequestProto{} }
func (m *AddBlockRequestProto) String() string { return proto.CompactTextString(m) }
func (*AddBlockRequestProto) ProtoMessage()    {}

const Default_AddBlockRequestProto_FileId uint64 = 0

func (m *AddBlockRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *AddBlockRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *AddBlockRequestProto) GetPrevious() *ExtendedBlockProto {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *AddBlockRequestProto) GetExcludeNodes() []*DatanodeInfoProto {
	if m != nil {
		return m.ExcludeNodes
	}
	return nil
}

func (m *AddBlockRequestProto) GetFileId() uint64 {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return Default_AddBlockRequestProto_FileId
}

func (m *AddBlockRequestProto) GetFavoredNodes() []string {
	if m != nil {
		return m.FavoredNodes
	}
	return nil
}

type AddBlockResponseProto struct {
	Block            *LocatedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AddBlockResponseProto) Reset()         { *m = AddBlockResponseProto{} }
func (m *AddBlockResponseProto) String() string { return proto.CompactTextString(m) }
func (*AddBlockResponseProto) ProtoMessage()    {}

func (m *AddBlockResponseProto) GetBlock() *LocatedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetAdditionalDatanodeRequestProto struct {
	Src                *string              `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Blk                *ExtendedBlockProto  `protobuf:"bytes,2,req,name=blk" json:"blk,omitempty"`
	Existings          []*DatanodeInfoProto `protobuf:"bytes,3,rep,name=existings" json:"existings,omitempty"`
	Excludes           []*DatanodeInfoProto `protobuf:"bytes,4,rep,name=excludes" json:"excludes,omitempty"`
	NumAdditionalNodes *uint32              `protobuf:"varint,5,req,name=numAdditionalNodes" json:"numAdditionalNodes,omitempty"`
	ClientName         *string              `protobuf:"bytes,6,req,name=clientName" json:"clientName,omitempty"`
	XXX_unrecognized   []byte               `json:"-"`
}

func (m *GetAdditionalDatanodeRequestProto) Reset()         { *m = GetAdditionalDatanodeRequestProto{} }
func (m *GetAdditionalDatanodeRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetAdditionalDatanodeRequestProto) ProtoMessage()    {}

func (m *GetAdditionalDatanodeRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *GetAdditionalDatanodeRequestProto) GetBlk() *ExtendedBlockProto {
	if m != nil {
		return m.Blk
	}
	return nil
}

func (m *GetAdditionalDatanodeRequestProto) GetExistings() []*DatanodeInfoProto {
	if m != nil {
		return m.Existings
	}
	return nil
}

func (m *GetAdditionalDatanodeRequestProto) GetExcludes() []*DatanodeInfoProto {
	if m != nil {
		return m.Excludes
	}
	return nil
}

func (m *GetAdditionalDatanodeRequestProto) GetNumAdditionalNodes() uint32 {
	if m != nil && m.NumAdditionalNodes != nil {
		return *m.NumAdditionalNodes
	}
	return 0
}

func (m *GetAdditionalDatanodeRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

type GetAdditionalDatanodeResponseProto struct {
	Block            *LocatedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetAdditionalDatanodeResponseProto) Reset()         { *m = GetAdditionalDatanodeResponseProto{} }
func (m *GetAdditionalDatanodeResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetAdditionalDatanodeResponseProto) ProtoMessage()    {}

func (m *GetAdditionalDatanodeResponseProto) GetBlock() *LocatedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

type CompleteRequestProto struct {
	Src              *string             `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	ClientName       *string             `protobuf:"bytes,2,req,name=clientName" json:"clientName,omitempty"`
	Last             *ExtendedBlockProto `protobuf:"bytes,3,opt,name=last" json:"last,omitempty"`
	FileId           *uint64             `protobuf:"varint,4,opt,name=fileId,def=0" json:"fileId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *CompleteRequestProto) Reset()         { *m = CompleteRequestProto{} }
func (m *CompleteRequestProto) String() string { return proto.CompactTextString(m) }
func (*CompleteRequestProto) ProtoMessage()    {}

const Default_CompleteRequestProto_FileId uint64 = 0

func (m *CompleteRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *CompleteRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *CompleteRequestProto) GetLast() *ExtendedBlockProto {
	if m != nil {
		return m.Last
	}
	return nil
}

func (m *CompleteRequestProto) GetFileId() uint64 {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return Default_CompleteRequestProto_FileId
}

type CompleteResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CompleteResponseProto) Reset()         { *m = CompleteResponseProto{} }
func (m *CompleteResponseProto) String() string { return proto.CompactTextString(m) }
func (*CompleteResponseProto) ProtoMessage()    {}

func (m *CompleteResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type ReportBadBlocksRequestProto struct {
	Blocks           []*LocatedBlockProto `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ReportBadBlocksRequestProto) Reset()         { *m = ReportBadBlocksRequestProto{} }
func (m *ReportBadBlocksRequestProto) String() string { return proto.CompactTextString(m) }
func (*ReportBadBlocksRequestProto) ProtoMessage()    {}

func (m *ReportBadBlocksRequestProto) GetBlocks() []*LocatedBlockProto {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type ReportBadBlocksResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReportBadBlocksResponseProto) Reset()         { *m = ReportBadBlocksResponseProto{} }
func (m *ReportBadBlocksResponseProto) String() string { return proto.CompactTextString(m) }
func (*ReportBadBlocksResponseProto) ProtoMessage()    {}

type ConcatRequestProto struct {
	Trg              *string  `protobuf:"bytes,1,req,name=trg" json:"trg,omitempty"`
	Srcs             []string `protobuf:"bytes,2,rep,name=srcs" json:"srcs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ConcatRequestProto) Reset()         { *m = ConcatRequestProto{} }
func (m *ConcatRequestProto) String() string { return proto.CompactTextString(m) }
func (*ConcatRequestProto) ProtoMessage()    {}

func (m *ConcatRequestProto) GetTrg() string {
	if m != nil && m.Trg != nil {
		return *m.Trg
	}
	return ""
}

func (m *ConcatRequestProto) GetSrcs() []string {
	if m != nil {
		return m.Srcs
	}
	return nil
}

type ConcatResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConcatResponseProto) Reset()         { *m = ConcatResponseProto{} }
func (m *ConcatResponseProto) String() string { return proto.CompactTextString(m) }
func (*ConcatResponseProto) ProtoMessage()    {}

type RenameRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Dst              *string `protobuf:"bytes,2,req,name=dst" json:"dst,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RenameRequestProto) Reset()         { *m = RenameRequestProto{} }
func (m *RenameRequestProto) String() string { return proto.CompactTextString(m) }
func (*RenameRequestProto) ProtoMessage()    {}

func (m *RenameRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *RenameRequestProto) GetDst() string {
	if m != nil && m.Dst != nil {
		return *m.Dst
	}
	return ""
}

type RenameResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RenameResponseProto) Reset()         { *m = RenameResponseProto{} }
func (m *RenameResponseProto) String() string { return proto.CompactTextString(m) }
func (*RenameResponseProto) ProtoMessage()    {}

func (m *RenameResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type Rename2RequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Dst              *string `protobuf:"bytes,2,req,name=dst" json:"dst,omitempty"`
	OverwriteDest    *bool   `protobuf:"varint,3,req,name=overwriteDest" json:"overwriteDest,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Rename2RequestProto) Reset()         { *m = Rename2RequestProto{} }
func (m *Rename2RequestProto) String() string { return proto.CompactTextString(m) }
func (*Rename2RequestProto) ProtoMessage()    {}

func (m *Rename2RequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *Rename2RequestProto) GetDst() string {
	if m != nil && m.Dst != nil {
		return *m.Dst
	}
	return ""
}

func (m *Rename2RequestProto) GetOverwriteDest() bool {
	if m != nil && m.OverwriteDest != nil {
		return *m.OverwriteDest
	}
	return false
}

type Rename2ResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Rename2ResponseProto) Reset()         { *m = Rename2ResponseProto{} }
func (m *Rename2ResponseProto) String() string { return proto.CompactTextString(m) }
func (*Rename2ResponseProto) ProtoMessage()    {}

type DeleteRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Recursive        *bool   `protobuf:"varint,2,req,name=recursive" json:"recursive,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteRequestProto) Reset()         { *m = DeleteRequestProto{} }
func (m *DeleteRequestProto) String() string { return proto.CompactTextString(m) }
func (*DeleteRequestProto) ProtoMessage()    {}

func (m *DeleteRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *DeleteRequestProto) GetRecursive() bool {
	if m != nil && m.Recursive != nil {
		return *m.Recursive
	}
	return false
}

type DeleteResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteResponseProto) Reset()         { *m = DeleteResponseProto{} }
func (m *DeleteResponseProto) String() string { return proto.CompactTextString(m) }
func (*DeleteResponseProto) ProtoMessage()    {}

func (m *DeleteResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type MkdirsRequestProto struct {
	Src              *string            `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Masked           *FsPermissionProto `protobuf:"bytes,2,req,name=masked" json:"masked,omitempty"`
	CreateParent     *bool              `protobuf:"varint,3,req,name=createParent" json:"createParent,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MkdirsRequestProto) Reset()         { *m = MkdirsRequestProto{} }
func (m *MkdirsRequestProto) String() string { return proto.CompactTextString(m) }
func (*MkdirsRequestProto) ProtoMessage()    {}

func (m *MkdirsRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *MkdirsRequestProto) GetMasked() *FsPermissionProto {
	if m != nil {
		return m.Masked
	}
	return nil
}

func (m *MkdirsRequestProto) GetCreateParent() bool {
	if m != nil && m.CreateParent != nil {
		return *m.CreateParent
	}
	return false
}

type MkdirsResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MkdirsResponseProto) Reset()         { *m = MkdirsResponseProto{} }
func (m *MkdirsResponseProto) String() string { return proto.CompactTextString(m) }
func (*MkdirsResponseProto) ProtoMessage()    {}

func (m *MkdirsResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type GetListingRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	StartAfter       []byte  `protobuf:"bytes,2,req,name=startAfter" json:"startAfter,omitempty"`
	NeedLocation     *bool   `protobuf:"varint,3,req,name=needLocation" json:"needLocation,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetListingRequestProto) Reset()         { *m = GetListingRequestProto{} }
func (m *GetListingRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetListingRequestProto) ProtoMessage()    {}

func (m *GetListingRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *GetListingRequestProto) GetStartAfter() []byte {
	if m != nil {
		return m.StartAfter
	}
	return nil
}

func (m *GetListingRequestProto) GetNeedLocation() bool {
	if m != nil && m.NeedLocation != nil {
		return *m.NeedLocation
	}
	return false
}

type GetListingResponseProto struct {
	DirList          *DirectoryListingProto `protobuf:"bytes,1,opt,name=dirList" json:"dirList,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *GetListingResponseProto) Reset()         { *m = GetListingResponseProto{} }
func (m *GetListingResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetListingResponseProto) ProtoMessage()    {}

func (m *GetListingResponseProto) GetDirList() *DirectoryListingProto {
	if m != nil {
		return m.DirList
	}
	return nil
}

type GetSnapshottableDirListingRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetSnapshottableDirListingRequestProto) Reset() {
	*m = GetSnapshottableDirListingRequestProto{}
}
func (m *GetSnapshottableDirListingRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetSnapshottableDirListingRequestProto) ProtoMessage()    {}

type GetSnapshottableDirListingResponseProto struct {
	SnapshottableDirList *SnapshottableDirectoryListingProto `protobuf:"bytes,1,opt,name=snapshottableDirList" json:"snapshottableDirList,omitempty"`
	XXX_unrecognized     []byte                              `json:"-"`
}

func (m *GetSnapshottableDirListingResponseProto) Reset() {
	*m = GetSnapshottableDirListingResponseProto{}
}
func (m *GetSnapshottableDirListingResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetSnapshottableDirListingResponseProto) ProtoMessage()    {}

func (m *GetSnapshottableDirListingResponseProto) GetSnapshottableDirList() *SnapshottableDirectoryListingProto {
	if m != nil {
		return m.SnapshottableDirList
	}
	return nil
}

type GetSnapshotDiffReportRequestProto struct {
	SnapshotRoot     *string `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	FromSnapshot     *string `protobuf:"bytes,2,req,name=fromSnapshot" json:"fromSnapshot,omitempty"`
	ToSnapshot       *string `protobuf:"bytes,3,req,name=toSnapshot" json:"toSnapshot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetSnapshotDiffReportRequestProto) Reset()         { *m = GetSnapshotDiffReportRequestProto{} }
func (m *GetSnapshotDiffReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotDiffReportRequestProto) ProtoMessage()    {}

func (m *GetSnapshotDiffReportRequestProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *GetSnapshotDiffReportRequestProto) GetFromSnapshot() string {
	if m != nil && m.FromSnapshot != nil {
		return *m.FromSnapshot
	}
	return ""
}

func (m *GetSnapshotDiffReportRequestProto) GetToSnapshot() string {
	if m != nil && m.ToSnapshot != nil {
		return *m.ToSnapshot
	}
	return ""
}

type GetSnapshotDiffReportResponseProto struct {
	DiffReport       *SnapshotDiffReportProto `protobuf:"bytes,1,req,name=diffReport" json:"diffReport,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *GetSnapshotDiffReportResponseProto) Reset()         { *m = GetSnapshotDiffReportResponseProto{} }
func (m *GetSnapshotDiffReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotDiffReportResponseProto) ProtoMessage()    {}

func (m *GetSnapshotDiffReportResponseProto) GetDiffReport() *SnapshotDiffReportProto {
	if m != nil {
		return m.DiffReport
	}
	return nil
}

type RenewLeaseRequestProto struct {
	ClientName       *string `protobuf:"bytes,1,req,name=clientName" json:"clientName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RenewLeaseRequestProto) Reset()         { *m = RenewLeaseRequestProto{} }
func (m *RenewLeaseRequestProto) String() string { return proto.CompactTextString(m) }
func (*RenewLeaseRequestProto) ProtoMessage()    {}

func (m *RenewLeaseRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

type RenewLeaseResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RenewLeaseResponseProto) Reset()         { *m = RenewLeaseResponseProto{} }
func (m *RenewLeaseResponseProto) String() string { return proto.CompactTextString(m) }
func (*RenewLeaseResponseProto) ProtoMessage()    {}

type RecoverLeaseRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	ClientName       *string `protobuf:"bytes,2,req,name=clientName" json:"clientName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecoverLeaseRequestProto) Reset()         { *m = RecoverLeaseRequestProto{} }
func (m *RecoverLeaseRequestProto) String() string { return proto.CompactTextString(m) }
func (*RecoverLeaseRequestProto) ProtoMessage()    {}

func (m *RecoverLeaseRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *RecoverLeaseRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

type RecoverLeaseResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RecoverLeaseResponseProto) Reset()         { *m = RecoverLeaseResponseProto{} }
func (m *RecoverLeaseResponseProto) String() string { return proto.CompactTextString(m) }
func (*RecoverLeaseResponseProto) ProtoMessage()    {}

func (m *RecoverLeaseResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type GetFsStatusRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetFsStatusRequestProto) Reset()         { *m = GetFsStatusRequestProto{} }
func (m *GetFsStatusRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetFsStatusRequestProto) ProtoMessage()    {}

type GetFsStatsResponseProto struct {
	Capacity         *uint64 `protobuf:"varint,1,req,name=capacity" json:"capacity,omitempty"`
	Used             *uint64 `protobuf:"varint,2,req,name=used" json:"used,omitempty"`
	Remaining        *uint64 `protobuf:"varint,3,req,name=remaining" json:"remaining,omitempty"`
	UnderReplicated  *uint64 `protobuf:"varint,4,req,name=under_replicated" json:"under_replicated,omitempty"`
	CorruptBlocks    *uint64 `protobuf:"varint,5,req,name=corrupt_blocks" json:"corrupt_blocks,omitempty"`
	MissingBlocks    *uint64 `protobuf:"varint,6,req,name=missing_blocks" json:"missing_blocks,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetFsStatsResponseProto) Reset()         { *m = GetFsStatsResponseProto{} }
func (m *GetFsStatsResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetFsStatsResponseProto) ProtoMessage()    {}

func (m *GetFsStatsResponseProto) GetCapacity() uint64 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

func (m *GetFsStatsResponseProto) GetUsed() uint64 {
	if m != nil && m.Used != nil {
		return *m.Used
	}
	return 0
}

func (m *GetFsStatsResponseProto) GetRemaining() uint64 {
	if m != nil && m.Remaining != nil {
		return *m.Remaining
	}
	return 0
}

func (m *GetFsStatsResponseProto) GetUnderReplicated() uint64 {
	if m != nil && m.UnderReplicated != nil {
		return *m.UnderReplicated
	}
	return 0
}

func (m *GetFsStatsResponseProto) GetCorruptBlocks() uint64 {
	if m != nil && m.CorruptBlocks != nil {
		return *m.CorruptBlocks
	}
	return 0
}

func (m *GetFsStatsResponseProto) GetMissingBlocks() uint64 {
	if m != nil && m.MissingBlocks != nil {
		return *m.MissingBlocks
	}
	return 0
}

type GetDatanodeReportRequestProto struct {
	Type             *DatanodeReportTypeProto `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.DatanodeReportTypeProto" json:"type,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *GetDatanodeReportRequestProto) Reset()         { *m = GetDatanodeReportRequestProto{} }
func (m *GetDatanodeReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetDatanodeReportRequestProto) ProtoMessage()    {}

func (m *GetDatanodeReportRequestProto) GetType() DatanodeReportTypeProto {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return DatanodeReportTypeProto_ALL
}

type GetDatanodeReportResponseProto struct {
	Di               []*DatanodeInfoProto `protobuf:"bytes,1,rep,name=di" json:"di,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GetDatanodeReportResponseProto) Reset()         { *m = GetDatanodeReportResponseProto{} }
func (m *GetDatanodeReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetDatanodeReportResponseProto) ProtoMessage()    {}

func (m *GetDatanodeReportResponseProto) GetDi() []*DatanodeInfoProto {
	if m != nil {
		return m.Di
	}
	return nil
}

type GetPreferredBlockSizeRequestProto struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPreferredBlockSizeRequestProto) Reset()         { *m = GetPreferredBlockSizeRequestProto{} }
func (m *GetPreferredBlockSizeRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetPreferredBlockSizeRequestProto) ProtoMessage()    {}

func (m *GetPreferredBlockSizeRequestProto) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

type GetPreferredBlockSizeResponseProto struct {
	Bsize            *uint64 `protobuf:"varint,1,req,name=bsize" json:"bsize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPreferredBlockSizeResponseProto) Reset()         { *m = GetPreferredBlockSizeResponseProto{} }
func (m *GetPreferredBlockSizeResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetPreferredBlockSizeResponseProto) ProtoMessage()    {}

func (m *GetPreferredBlockSizeResponseProto) GetBsize() uint64 {
	if m != nil && m.Bsize != nil {
		return *m.Bsize
	}
	return 0
}

type SetSafeModeRequestProto struct {
	Action           *SafeModeActionProto `protobuf:"varint,1,req,name=action,enum=hadoop.hdfs.SafeModeActionProto" json:"action,omitempty"`
	Checked          *bool                `protobuf:"varint,2,opt,name=checked,def=0" json:"checked,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SetSafeModeRequestProto) Reset()         { *m = SetSafeModeRequestProto{} }
func (m *SetSafeModeRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetSafeModeRequestProto) ProtoMessage()    {}

const Default_SetSafeModeRequestProto_Checked bool = false

func (m *SetSafeModeRequestProto) GetAction() SafeModeActionProto {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return SafeModeActionProto_SAFEMODE_LEAVE
}

func (m *SetSafeModeRequestProto) GetChecked() bool {
	if m != nil && m.Checked != nil {
		return *m.Checked
	}
	return Default_SetSafeModeRequestProto_Checked
}

type SetSafeModeResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetSafeModeResponseProto) Reset()         { *m = SetSafeModeResponseProto{} }
func (m *SetSafeModeResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetSafeModeResponseProto) ProtoMessage()    {}

func (m *SetSafeModeResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type SaveNamespaceRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SaveNamespaceRequestProto) Reset()         { *m = SaveNamespaceRequestProto{} }
func (m *SaveNamespaceRequestProto) String() string { return proto.CompactTextString(m) }
func (*SaveNamespaceRequestProto) ProtoMessage()    {}

type SaveNamespaceResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SaveNamespaceResponseProto) Reset()         { *m = SaveNamespaceResponseProto{} }
func (m *SaveNamespaceResponseProto) String() string { return proto.CompactTextString(m) }
func (*SaveNamespaceResponseProto) ProtoMessage()    {}

type RollEditsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RollEditsRequestProto) Reset()         { *m = RollEditsRequestProto{} }
func (m *RollEditsRequestProto) String() string { return proto.CompactTextString(m) }
func (*RollEditsRequestProto) ProtoMessage()    {}

type RollEditsResponseProto struct {
	NewSegmentTxId   *uint64 `protobuf:"varint,1,req,name=newSegmentTxId" json:"newSegmentTxId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RollEditsResponseProto) Reset()         { *m = RollEditsResponseProto{} }
func (m *RollEditsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RollEditsResponseProto) ProtoMessage()    {}

func (m *RollEditsResponseProto) GetNewSegmentTxId() uint64 {
	if m != nil && m.NewSegmentTxId != nil {
		return *m.NewSegmentTxId
	}
	return 0
}

type RestoreFailedStorageRequestProto struct {
	Arg              *string `protobuf:"bytes,1,req,name=arg" json:"arg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RestoreFailedStorageRequestProto) Reset()         { *m = RestoreFailedStorageRequestProto{} }
func (m *RestoreFailedStorageRequestProto) String() string { return proto.CompactTextString(m) }
func (*RestoreFailedStorageRequestProto) ProtoMessage()    {}

func (m *RestoreFailedStorageRequestProto) GetArg() string {
	if m != nil && m.Arg != nil {
		return *m.Arg
	}
	return ""
}

type RestoreFailedStorageResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RestoreFailedStorageResponseProto) Reset()         { *m = RestoreFailedStorageResponseProto{} }
func (m *RestoreFailedStorageResponseProto) String() string { return proto.CompactTextString(m) }
func (*RestoreFailedStorageResponseProto) ProtoMessage()    {}

func (m *RestoreFailedStorageResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type RefreshNodesRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshNodesRequestProto) Reset()         { *m = RefreshNodesRequestProto{} }
func (m *RefreshNodesRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshNodesRequestProto) ProtoMessage()    {}

type RefreshNodesResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshNodesResponseProto) Reset()         { *m = RefreshNodesResponseProto{} }
func (m *RefreshNodesResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshNodesResponseProto) ProtoMessage()    {}

type FinalizeUpgradeRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinalizeUpgradeRequestProto) Reset()         { *m = FinalizeUpgradeRequestProto{} }
func (m *FinalizeUpgradeRequestProto) String() string { return proto.CompactTextString(m) }
func (*FinalizeUpgradeRequestProto) ProtoMessage()    {}

type FinalizeUpgradeResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinalizeUpgradeResponseProto) Reset()         { *m = FinalizeUpgradeResponseProto{} }
func (m *FinalizeUpgradeResponseProto) String() string { return proto.CompactTextString(m) }
func (*FinalizeUpgradeResponseProto) ProtoMessage()    {}

type ListCorruptFileBlocksRequestProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Cookie           *string `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListCorruptFileBlocksRequestProto) Reset()         { *m = ListCorruptFileBlocksRequestProto{} }
func (m *ListCorruptFileBlocksRequestProto) String() string { return proto.CompactTextString(m) }
func (*ListCorruptFileBlocksRequestProto) ProtoMessage()    {}

func (m *ListCorruptFileBlocksRequestProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *ListCorruptFileBlocksRequestProto) GetCookie() string {
	if m != nil && m.Cookie != nil {
		return *m.Cookie
	}
	return ""
}

type ListCorruptFileBlocksResponseProto struct {
	Corrupt          *CorruptFileBlocksProto `protobuf:"bytes,1,req,name=corrupt" json:"corrupt,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ListCorruptFileBlocksResponseProto) Reset()         { *m = ListCorruptFileBlocksResponseProto{} }
func (m *ListCorruptFileBlocksResponseProto) String() string { return proto.CompactTextString(m) }
func (*ListCorruptFileBlocksResponseProto) ProtoMessage()    {}

func (m *ListCorruptFileBlocksResponseProto) GetCorrupt() *CorruptFileBlocksProto {
	if m != nil {
		return m.Corrupt
	}
	return nil
}

type MetaSaveRequestProto struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MetaSaveRequestProto) Reset()         { *m = MetaSaveRequestProto{} }
func (m *MetaSaveRequestProto) String() string { return proto.CompactTextString(m) }
func (*MetaSaveRequestProto) ProtoMessage()    {}

func (m *MetaSaveRequestProto) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

type MetaSaveResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MetaSaveResponseProto) Reset()         { *m = MetaSaveResponseProto{} }
func (m *MetaSaveResponseProto) String() string { return proto.CompactTextString(m) }
func (*MetaSaveResponseProto) ProtoMessage()    {}

type GetFileInfoRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetFileInfoRequestProto) Reset()         { *m = GetFileInfoRequestProto{} }
func (m *GetFileInfoRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoRequestProto) ProtoMessage()    {}

func (m *GetFileInfoRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type GetFileInfoResponseProto struct {
	Fs               *HdfsFileStatusProto `protobuf:"bytes,1,opt,name=fs" json:"fs,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GetFileInfoResponseProto) Reset()         { *m = GetFileInfoResponseProto{} }
func (m *GetFileInfoResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoResponseProto) ProtoMessage()    {}

func (m *GetFileInfoResponseProto) GetFs() *HdfsFileStatusProto {
	if m != nil {
		return m.Fs
	}
	return nil
}

type IsFileClosedRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IsFileClosedRequestProto) Reset()         { *m = IsFileClosedRequestProto{} }
func (m *IsFileClosedRequestProto) String() string { return proto.CompactTextString(m) }
func (*IsFileClosedRequestProto) ProtoMessage()    {}

func (m *IsFileClosedRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type IsFileClosedResponseProto struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsFileClosedResponseProto) Reset()         { *m = IsFileClosedResponseProto{} }
func (m *IsFileClosedResponseProto) String() string { return proto.CompactTextString(m) }
func (*IsFileClosedResponseProto) ProtoMessage()    {}

func (m *IsFileClosedResponseProto) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type GetFileLinkInfoRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetFileLinkInfoRequestProto) Reset()         { *m = GetFileLinkInfoRequestProto{} }
func (m *GetFileLinkInfoRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetFileLinkInfoRequestProto) ProtoMessage()    {}

func (m *GetFileLinkInfoRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type GetFileLinkInfoResponseProto struct {
	Fs               *HdfsFileStatusProto `protobuf:"bytes,1,opt,name=fs" json:"fs,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GetFileLinkInfoResponseProto) Reset()         { *m = GetFileLinkInfoResponseProto{} }
func (m *GetFileLinkInfoResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetFileLinkInfoResponseProto) ProtoMessage()    {}

func (m *GetFileLinkInfoResponseProto) GetFs() *HdfsFileStatusProto {
	if m != nil {
		return m.Fs
	}
	return nil
}

type GetContentSummaryRequestProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetContentSummaryRequestProto) Reset()         { *m = GetContentSummaryRequestProto{} }
func (m *GetContentSummaryRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetContentSummaryRequestProto) ProtoMessage()    {}

func (m *GetContentSummaryRequestProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type GetContentSummaryResponseProto struct {
	Summary          *ContentSummaryProto `protobuf:"bytes,1,req,name=summary" json:"summary,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GetContentSummaryResponseProto) Reset()         { *m = GetContentSummaryResponseProto{} }
func (m *GetContentSummaryResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetContentSummaryResponseProto) ProtoMessage()    {}

func (m *GetContentSummaryResponseProto) GetSummary() *ContentSummaryProto {
	if m != nil {
		return m.Summary
	}
	return nil
}

type SetQuotaRequestProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	NamespaceQuota   *uint64 `protobuf:"varint,2,req,name=namespaceQuota" json:"namespaceQuota,omitempty"`
	DiskspaceQuota   *uint64 `protobuf:"varint,3,req,name=diskspaceQuota" json:"diskspaceQuota,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetQuotaRequestProto) Reset()         { *m = SetQuotaRequestProto{} }
func (m *SetQuotaRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetQuotaRequestProto) ProtoMessage()    {}

func (m *SetQuotaRequestProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *SetQuotaRequestProto) GetNamespaceQuota() uint64 {
	if m != nil && m.NamespaceQuota != nil {
		return *m.NamespaceQuota
	}
	return 0
}

func (m *SetQuotaRequestProto) GetDiskspaceQuota() uint64 {
	if m != nil && m.DiskspaceQuota != nil {
		return *m.DiskspaceQuota
	}
	return 0
}

type SetQuotaResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetQuotaResponseProto) Reset()         { *m = SetQuotaResponseProto{} }
func (m *SetQuotaResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetQuotaResponseProto) ProtoMessage()    {}

type FsyncRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Client           *string `protobuf:"bytes,2,req,name=client" json:"client,omitempty"`
	LastBlockLength  *int64  `protobuf:"zigzag64,3,opt,name=lastBlockLength,def=-1" json:"lastBlockLength,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FsyncRequestProto) Reset()         { *m = FsyncRequestProto{} }
func (m *FsyncRequestProto) String() string { return proto.CompactTextString(m) }
func (*FsyncRequestProto) ProtoMessage()    {}

const Default_FsyncRequestProto_LastBlockLength int64 = -1

func (m *FsyncRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *FsyncRequestProto) GetClient() string {
	if m != nil && m.Client != nil {
		return *m.Client
	}
	return ""
}

func (m *FsyncRequestProto) GetLastBlockLength() int64 {
	if m != nil && m.LastBlockLength != nil {
		return *m.LastBlockLength
	}
	return Default_FsyncRequestProto_LastBlockLength
}

type FsyncResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FsyncResponseProto) Reset()         { *m = FsyncResponseProto{} }
func (m *FsyncResponseProto) String() string { return proto.CompactTextString(m) }
func (*FsyncResponseProto) ProtoMessage()    {}

type SetTimesRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Mtime            *uint64 `protobuf:"varint,2,req,name=mtime" json:"mtime,omitempty"`
	Atime            *uint64 `protobuf:"varint,3,req,name=atime" json:"atime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetTimesRequestProto) Reset()         { *m = SetTimesRequestProto{} }
func (m *SetTimesRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetTimesRequestProto) ProtoMessage()    {}

func (m *SetTimesRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetTimesRequestProto) GetMtime() uint64 {
	if m != nil && m.Mtime != nil {
		return *m.Mtime
	}
	return 0
}

func (m *SetTimesRequestProto) GetAtime() uint64 {
	if m != nil && m.Atime != nil {
		return *m.Atime
	}
	return 0
}

type SetTimesResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetTimesResponseProto) Reset()         { *m = SetTimesResponseProto{} }
func (m *SetTimesResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetTimesResponseProto) ProtoMessage()    {}

type CreateSymlinkRequestProto struct {
	Target           *string            `protobuf:"bytes,1,req,name=target" json:"target,omitempty"`
	Link             *string            `protobuf:"bytes,2,req,name=link" json:"link,omitempty"`
	DirPerm          *FsPermissionProto `protobuf:"bytes,3,req,name=dirPerm" json:"dirPerm,omitempty"`
	CreateParent     *bool              `protobuf:"varint,4,req,name=createParent" json:"createParent,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *CreateSymlinkRequestProto) Reset()         { *m = CreateSymlinkRequestProto{} }
func (m *CreateSymlinkRequestProto) String() string { return proto.CompactTextString(m) }
func (*CreateSymlinkRequestProto) ProtoMessage()    {}

func (m *CreateSymlinkRequestProto) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *CreateSymlinkRequestProto) GetLink() string {
	if m != nil && m.Link != nil {
		return *m.Link
	}
	return ""
}

func (m *CreateSymlinkRequestProto) GetDirPerm() *FsPermissionProto {
	if m != nil {
		return m.DirPerm
	}
	return nil
}

func (m *CreateSymlinkRequestProto) GetCreateParent() bool {
	if m != nil && m.CreateParent != nil {
		return *m.CreateParent
	}
	return false
}

type CreateSymlinkResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateSymlinkResponseProto) Reset()         { *m = CreateSymlinkResponseProto{} }
func (m *CreateSymlinkResponseProto) String() string { return proto.CompactTextString(m) }
func (*CreateSymlinkResponseProto) ProtoMessage()    {}

type GetLinkTargetRequestProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLinkTargetRequestProto) Reset()         { *m = GetLinkTargetRequestProto{} }
func (m *GetLinkTargetRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetLinkTargetRequestProto) ProtoMessage()    {}

func (m *GetLinkTargetRequestProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type GetLinkTargetResponseProto struct {
	TargetPath       *string `protobuf:"bytes,1,opt,name=targetPath" json:"targetPath,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLinkTargetResponseProto) Reset()         { *m = GetLinkTargetResponseProto{} }
func (m *GetLinkTargetResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetLinkTargetResponseProto) ProtoMessage()    {}

func (m *GetLinkTargetResponseProto) GetTargetPath() string {
	if m != nil && m.TargetPath != nil {
		return *m.TargetPath
	}
	return ""
}

type UpdateBlockForPipelineRequestProto struct {
	Block            *ExtendedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	ClientName       *string             `protobuf:"bytes,2,req,name=clientName" json:"clientName,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UpdateBlockForPipelineRequestProto) Reset()         { *m = UpdateBlockForPipelineRequestProto{} }
func (m *UpdateBlockForPipelineRequestProto) String() string { return proto.CompactTextString(m) }
func (*UpdateBlockForPipelineRequestProto) ProtoMessage()    {}

func (m *UpdateBlockForPipelineRequestProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *UpdateBlockForPipelineRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

type UpdateBlockForPipelineResponseProto struct {
	Block            *LocatedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UpdateBlockForPipelineResponseProto) Reset()         { *m = UpdateBlockForPipelineResponseProto{} }
func (m *UpdateBlockForPipelineResponseProto) String() string { return proto.CompactTextString(m) }
func (*UpdateBlockForPipelineResponseProto) ProtoMessage()    {}

func (m *UpdateBlockForPipelineResponseProto) GetBlock() *LocatedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

type UpdatePipelineRequestProto struct {
	ClientName       *string             `protobuf:"bytes,1,req,name=clientName" json:"clientName,omitempty"`
	OldBlock         *ExtendedBlockProto `protobuf:"bytes,2,req,name=oldBlock" json:"oldBlock,omitempty"`
	NewBlock         *ExtendedBlockProto `protobuf:"bytes,3,req,name=newBlock" json:"newBlock,omitempty"`
	NewNodes         []*DatanodeIDProto  `protobuf:"bytes,4,rep,name=newNodes" json:"newNodes,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UpdatePipelineRequestProto) Reset()         { *m = UpdatePipelineRequestProto{} }
func (m *UpdatePipelineRequestProto) String() string { return proto.CompactTextString(m) }
func (*UpdatePipelineRequestProto) ProtoMessage()    {}

func (m *UpdatePipelineRequestProto) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *UpdatePipelineRequestProto) GetOldBlock() *ExtendedBlockProto {
	if m != nil {
		return m.OldBlock
	}
	return nil
}

func (m *UpdatePipelineRequestProto) GetNewBlock() *ExtendedBlockProto {
	if m != nil {
		return m.NewBlock
	}
	return nil
}

func (m *UpdatePipelineRequestProto) GetNewNodes() []*DatanodeIDProto {
	if m != nil {
		return m.NewNodes
	}
	return nil
}

type UpdatePipelineResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdatePipelineResponseProto) Reset()         { *m = UpdatePipelineResponseProto{} }
func (m *UpdatePipelineResponseProto) String() string { return proto.CompactTextString(m) }
func (*UpdatePipelineResponseProto) ProtoMessage()    {}

type SetBalancerBandwidthRequestProto struct {
	Bandwidth        *int64 `protobuf:"varint,1,req,name=bandwidth" json:"bandwidth,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetBalancerBandwidthRequestProto) Reset()         { *m = SetBalancerBandwidthRequestProto{} }
func (m *SetBalancerBandwidthRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetBalancerBandwidthRequestProto) ProtoMessage()    {}

func (m *SetBalancerBandwidthRequestProto) GetBandwidth() int64 {
	if m != nil && m.Bandwidth != nil {
		return *m.Bandwidth
	}
	return 0
}

type SetBalancerBandwidthResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetBalancerBandwidthResponseProto) Reset()         { *m = SetBalancerBandwidthResponseProto{} }
func (m *SetBalancerBandwidthResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetBalancerBandwidthResponseProto) ProtoMessage()    {}

type GetDataEncryptionKeyRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetDataEncryptionKeyRequestProto) Reset()         { *m = GetDataEncryptionKeyRequestProto{} }
func (m *GetDataEncryptionKeyRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetDataEncryptionKeyRequestProto) ProtoMessage()    {}

type GetDataEncryptionKeyResponseProto struct {
	DataEncryptionKey *DataEncryptionKeyProto `protobuf:"bytes,1,opt,name=dataEncryptionKey" json:"dataEncryptionKey,omitempty"`
	XXX_unrecognized  []byte                  `json:"-"`
}

func (m *GetDataEncryptionKeyResponseProto) Reset()         { *m = GetDataEncryptionKeyResponseProto{} }
func (m *GetDataEncryptionKeyResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetDataEncryptionKeyResponseProto) ProtoMessage()    {}

func (m *GetDataEncryptionKeyResponseProto) GetDataEncryptionKey() *DataEncryptionKeyProto {
	if m != nil {
		return m.DataEncryptionKey
	}
	return nil
}

type CreateSnapshotRequestProto struct {
	SnapshotRoot     *string `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	SnapshotName     *string `protobuf:"bytes,2,opt,name=snapshotName" json:"snapshotName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateSnapshotRequestProto) Reset()         { *m = CreateSnapshotRequestProto{} }
func (m *CreateSnapshotRequestProto) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotRequestProto) ProtoMessage()    {}

func (m *CreateSnapshotRequestProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *CreateSnapshotRequestProto) GetSnapshotName() string {
	if m != nil && m.SnapshotName != nil {
		return *m.SnapshotName
	}
	return ""
}

type CreateSnapshotResponseProto struct {
	SnapshotPath     *string `protobuf:"bytes,1,req,name=snapshotPath" json:"snapshotPath,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateSnapshotResponseProto) Reset()         { *m = CreateSnapshotResponseProto{} }
func (m *CreateSnapshotResponseProto) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotResponseProto) ProtoMessage()    {}

func (m *CreateSnapshotResponseProto) GetSnapshotPath() string {
	if m != nil && m.SnapshotPath != nil {
		return *m.SnapshotPath
	}
	return ""
}

type RenameSnapshotRequestProto struct {
	SnapshotRoot     *string `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	SnapshotOldName  *string `protobuf:"bytes,2,req,name=snapshotOldName" json:"snapshotOldName,omitempty"`
	SnapshotNewName  *string `protobuf:"bytes,3,req,name=snapshotNewName" json:"snapshotNewName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RenameSnapshotRequestProto) Reset()         { *m = RenameSnapshotRequestProto{} }
func (m *RenameSnapshotRequestProto) String() string { return proto.CompactTextString(m) }
func (*RenameSnapshotRequestProto) ProtoMessage()    {}

func (m *RenameSnapshotRequestProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *RenameSnapshotRequestProto) GetSnapshotOldName() string {
	if m != nil && m.SnapshotOldName != nil {
		return *m.SnapshotOldName
	}
	return ""
}

func (m *RenameSnapshotRequestProto) GetSnapshotNewName() string {
	if m != nil && m.SnapshotNewName != nil {
		return *m.SnapshotNewName
	}
	return ""
}

type RenameSnapshotResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RenameSnapshotResponseProto) Reset()         { *m = RenameSnapshotResponseProto{} }
func (m *RenameSnapshotResponseProto) String() string { return proto.CompactTextString(m) }
func (*RenameSnapshotResponseProto) ProtoMessage()    {}

type AllowSnapshotRequestProto struct {
	SnapshotRoot     *string `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllowSnapshotRequestProto) Reset()         { *m = AllowSnapshotRequestProto{} }
func (m *AllowSnapshotRequestProto) String() string { return proto.CompactTextString(m) }
func (*AllowSnapshotRequestProto) ProtoMessage()    {}

func (m *AllowSnapshotRequestProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

type AllowSnapshotResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AllowSnapshotResponseProto) Reset()         { *m = AllowSnapshotResponseProto{} }
func (m *AllowSnapshotResponseProto) String() string { return proto.CompactTextString(m) }
func (*AllowSnapshotResponseProto) ProtoMessage()    {}

type DisallowSnapshotRequestProto struct {
	SnapshotRoot     *string `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DisallowSnapshotRequestProto) Reset()         { *m = DisallowSnapshotRequestProto{} }
func (m *DisallowSnapshotRequestProto) String() string { return proto.CompactTextString(m) }
func (*DisallowSnapshotRequestProto) ProtoMessage()    {}

func (m *DisallowSnapshotRequestProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

type DisallowSnapshotResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DisallowSnapshotResponseProto) Reset()         { *m = DisallowSnapshotResponseProto{} }
func (m *DisallowSnapshotResponseProto) String() string { return proto.CompactTextString(m) }
func (*DisallowSnapshotResponseProto) ProtoMessage()    {}

type DeleteSnapshotRequestProto struct {
	SnapshotRoot     *string `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	SnapshotName     *string `protobuf:"bytes,2,req,name=snapshotName" json:"snapshotName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteSnapshotRequestProto) Reset()         { *m = DeleteSnapshotRequestProto{} }
func (m *DeleteSnapshotRequestProto) String() string { return proto.CompactTextString(m) }
func (*DeleteSnapshotRequestProto) ProtoMessage()    {}

func (m *DeleteSnapshotRequestProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *DeleteSnapshotRequestProto) GetSnapshotName() string {
	if m != nil && m.SnapshotName != nil {
		return *m.SnapshotName
	}
	return ""
}

type DeleteSnapshotResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteSnapshotResponseProto) Reset()         { *m = DeleteSnapshotResponseProto{} }
func (m *DeleteSnapshotResponseProto) String() string { return proto.CompactTextString(m) }
func (*DeleteSnapshotResponseProto) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("hadoop.hdfs.CreateFlagProto", CreateFlagProto_name, CreateFlagProto_value)
	proto.RegisterEnum("hadoop.hdfs.DatanodeReportTypeProto", DatanodeReportTypeProto_name, DatanodeReportTypeProto_value)
	proto.RegisterEnum("hadoop.hdfs.SafeModeActionProto", SafeModeActionProto_name, SafeModeActionProto_value)
}
