// Code generated by protoc-gen-go.
// source: hdfs.proto
// DO NOT EDIT!

package hadoop_hdfs

import proto "github.com/golang/protobuf/proto"
import math "math"
import hadoop_common "github.com/colinmarc/hdfs/protocol/hadoop_common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// *
// Checksum algorithms/types used in HDFS
// Make sure this enum's integer values match enum values' id properties defined
// in org.apache.hadoop.util.DataChecksum.Type
type ChecksumTypeProto int32

const (
	ChecksumTypeProto_CHECKSUM_NULL   ChecksumTypeProto = 0
	ChecksumTypeProto_CHECKSUM_CRC32  ChecksumTypeProto = 1
	ChecksumTypeProto_CHECKSUM_CRC32C ChecksumTypeProto = 2
)

var ChecksumTypeProto_name = map[int32]string{
	0: "CHECKSUM_NULL",
	1: "CHECKSUM_CRC32",
	2: "CHECKSUM_CRC32C",
}
var ChecksumTypeProto_value = map[string]int32{
	"CHECKSUM_NULL":   0,
	"CHECKSUM_CRC32":  1,
	"CHECKSUM_CRC32C": 2,
}

func (x ChecksumTypeProto) Enum() *ChecksumTypeProto {
	p := new(ChecksumTypeProto)
	*p = x
	return p
}
func (x ChecksumTypeProto) String() string {
	return proto.EnumName(ChecksumTypeProto_name, int32(x))
}
func (x *ChecksumTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChecksumTypeProto_value, data, "ChecksumTypeProto")
	if err != nil {
		return err
	}
	*x = ChecksumTypeProto(value)
	return nil
}

// *
// State of a block replica at a datanode
type ReplicaStateProto int32

const (
	ReplicaStateProto_FINALIZED ReplicaStateProto = 0
	ReplicaStateProto_RBW       ReplicaStateProto = 1
	ReplicaStateProto_RWR       ReplicaStateProto = 2
	ReplicaStateProto_RUR       ReplicaStateProto = 3
	ReplicaStateProto_TEMPORARY ReplicaStateProto = 4
)

var ReplicaStateProto_name = map[int32]string{
	0: "FINALIZED",
	1: "RBW",
	2: "RWR",
	3: "RUR",
	4: "TEMPORARY",
}
var ReplicaStateProto_value = map[string]int32{
	"FINALIZED": 0,
	"RBW":       1,
	"RWR":       2,
	"RUR":       3,
	"TEMPORARY": 4,
}

func (x ReplicaStateProto) Enum() *ReplicaStateProto {
	p := new(ReplicaStateProto)
	*p = x
	return p
}
func (x ReplicaStateProto) String() string {
	return proto.EnumName(ReplicaStateProto_name, int32(x))
}
func (x *ReplicaStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReplicaStateProto_value, data, "ReplicaStateProto")
	if err != nil {
		return err
	}
	*x = ReplicaStateProto(value)
	return nil
}

type DatanodeInfoProto_AdminState int32

const (
	DatanodeInfoProto_NORMAL                  DatanodeInfoProto_AdminState = 0
	DatanodeInfoProto_DECOMMISSION_INPROGRESS DatanodeInfoProto_AdminState = 1
	DatanodeInfoProto_DECOMMISSIONED          DatanodeInfoProto_AdminState = 2
)

var DatanodeInfoProto_AdminState_name = map[int32]string{
	0: "NORMAL",
	1: "DECOMMISSION_INPROGRESS",
	2: "DECOMMISSIONED",
}
var DatanodeInfoProto_AdminState_value = map[string]int32{
	"NORMAL":                  0,
	"DECOMMISSION_INPROGRESS": 1,
	"DECOMMISSIONED":          2,
}

func (x DatanodeInfoProto_AdminState) Enum() *DatanodeInfoProto_AdminState {
	p := new(DatanodeInfoProto_AdminState)
	*p = x
	return p
}
func (x DatanodeInfoProto_AdminState) String() string {
	return proto.EnumName(DatanodeInfoProto_AdminState_name, int32(x))
}
func (x *DatanodeInfoProto_AdminState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DatanodeInfoProto_AdminState_value, data, "DatanodeInfoProto_AdminState")
	if err != nil {
		return err
	}
	*x = DatanodeInfoProto_AdminState(value)
	return nil
}

type HdfsFileStatusProto_FileType int32

const (
	HdfsFileStatusProto_IS_DIR     HdfsFileStatusProto_FileType = 1
	HdfsFileStatusProto_IS_FILE    HdfsFileStatusProto_FileType = 2
	HdfsFileStatusProto_IS_SYMLINK HdfsFileStatusProto_FileType = 3
)

var HdfsFileStatusProto_FileType_name = map[int32]string{
	1: "IS_DIR",
	2: "IS_FILE",
	3: "IS_SYMLINK",
}
var HdfsFileStatusProto_FileType_value = map[string]int32{
	"IS_DIR":     1,
	"IS_FILE":    2,
	"IS_SYMLINK": 3,
}

func (x HdfsFileStatusProto_FileType) Enum() *HdfsFileStatusProto_FileType {
	p := new(HdfsFileStatusProto_FileType)
	*p = x
	return p
}
func (x HdfsFileStatusProto_FileType) String() string {
	return proto.EnumName(HdfsFileStatusProto_FileType_name, int32(x))
}
func (x *HdfsFileStatusProto_FileType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HdfsFileStatusProto_FileType_value, data, "HdfsFileStatusProto_FileType")
	if err != nil {
		return err
	}
	*x = HdfsFileStatusProto_FileType(value)
	return nil
}

type NamenodeRegistrationProto_NamenodeRoleProto int32

const (
	NamenodeRegistrationProto_NAMENODE   NamenodeRegistrationProto_NamenodeRoleProto = 1
	NamenodeRegistrationProto_BACKUP     NamenodeRegistrationProto_NamenodeRoleProto = 2
	NamenodeRegistrationProto_CHECKPOINT NamenodeRegistrationProto_NamenodeRoleProto = 3
)

var NamenodeRegistrationProto_NamenodeRoleProto_name = map[int32]string{
	1: "NAMENODE",
	2: "BACKUP",
	3: "CHECKPOINT",
}
var NamenodeRegistrationProto_NamenodeRoleProto_value = map[string]int32{
	"NAMENODE":   1,
	"BACKUP":     2,
	"CHECKPOINT": 3,
}

func (x NamenodeRegistrationProto_NamenodeRoleProto) Enum() *NamenodeRegistrationProto_NamenodeRoleProto {
	p := new(NamenodeRegistrationProto_NamenodeRoleProto)
	*p = x
	return p
}
func (x NamenodeRegistrationProto_NamenodeRoleProto) String() string {
	return proto.EnumName(NamenodeRegistrationProto_NamenodeRoleProto_name, int32(x))
}
func (x *NamenodeRegistrationProto_NamenodeRoleProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NamenodeRegistrationProto_NamenodeRoleProto_value, data, "NamenodeRegistrationProto_NamenodeRoleProto")
	if err != nil {
		return err
	}
	*x = NamenodeRegistrationProto_NamenodeRoleProto(value)
	return nil
}

type NamenodeCommandProto_Type int32

const (
	NamenodeCommandProto_NamenodeCommand   NamenodeCommandProto_Type = 0
	NamenodeCommandProto_CheckPointCommand NamenodeCommandProto_Type = 1
)

var NamenodeCommandProto_Type_name = map[int32]string{
	0: "NamenodeCommand",
	1: "CheckPointCommand",
}
var NamenodeCommandProto_Type_value = map[string]int32{
	"NamenodeCommand":   0,
	"CheckPointCommand": 1,
}

func (x NamenodeCommandProto_Type) Enum() *NamenodeCommandProto_Type {
	p := new(NamenodeCommandProto_Type)
	*p = x
	return p
}
func (x NamenodeCommandProto_Type) String() string {
	return proto.EnumName(NamenodeCommandProto_Type_name, int32(x))
}
func (x *NamenodeCommandProto_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NamenodeCommandProto_Type_value, data, "NamenodeCommandProto_Type")
	if err != nil {
		return err
	}
	*x = NamenodeCommandProto_Type(value)
	return nil
}

// *
// Extended block idenfies a block
type ExtendedBlockProto struct {
	PoolId           *string `protobuf:"bytes,1,req,name=poolId" json:"poolId,omitempty"`
	BlockId          *uint64 `protobuf:"varint,2,req,name=blockId" json:"blockId,omitempty"`
	GenerationStamp  *uint64 `protobuf:"varint,3,req,name=generationStamp" json:"generationStamp,omitempty"`
	NumBytes         *uint64 `protobuf:"varint,4,opt,name=numBytes,def=0" json:"numBytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExtendedBlockProto) Reset()         { *m = ExtendedBlockProto{} }
func (m *ExtendedBlockProto) String() string { return proto.CompactTextString(m) }
func (*ExtendedBlockProto) ProtoMessage()    {}

const Default_ExtendedBlockProto_NumBytes uint64 = 0

func (m *ExtendedBlockProto) GetPoolId() string {
	if m != nil && m.PoolId != nil {
		return *m.PoolId
	}
	return ""
}

func (m *ExtendedBlockProto) GetBlockId() uint64 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *ExtendedBlockProto) GetGenerationStamp() uint64 {
	if m != nil && m.GenerationStamp != nil {
		return *m.GenerationStamp
	}
	return 0
}

func (m *ExtendedBlockProto) GetNumBytes() uint64 {
	if m != nil && m.NumBytes != nil {
		return *m.NumBytes
	}
	return Default_ExtendedBlockProto_NumBytes
}

// *
// Identifies a Datanode
type DatanodeIDProto struct {
	IpAddr           *string `protobuf:"bytes,1,req,name=ipAddr" json:"ipAddr,omitempty"`
	HostName         *string `protobuf:"bytes,2,req,name=hostName" json:"hostName,omitempty"`
	StorageID        *string `protobuf:"bytes,3,req,name=storageID" json:"storageID,omitempty"`
	XferPort         *uint32 `protobuf:"varint,4,req,name=xferPort" json:"xferPort,omitempty"`
	InfoPort         *uint32 `protobuf:"varint,5,req,name=infoPort" json:"infoPort,omitempty"`
	IpcPort          *uint32 `protobuf:"varint,6,req,name=ipcPort" json:"ipcPort,omitempty"`
	InfoSecurePort   *uint32 `protobuf:"varint,7,opt,name=infoSecurePort,def=0" json:"infoSecurePort,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DatanodeIDProto) Reset()         { *m = DatanodeIDProto{} }
func (m *DatanodeIDProto) String() string { return proto.CompactTextString(m) }
func (*DatanodeIDProto) ProtoMessage()    {}

const Default_DatanodeIDProto_InfoSecurePort uint32 = 0

func (m *DatanodeIDProto) GetIpAddr() string {
	if m != nil && m.IpAddr != nil {
		return *m.IpAddr
	}
	return ""
}

func (m *DatanodeIDProto) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

func (m *DatanodeIDProto) GetStorageID() string {
	if m != nil && m.StorageID != nil {
		return *m.StorageID
	}
	return ""
}

func (m *DatanodeIDProto) GetXferPort() uint32 {
	if m != nil && m.XferPort != nil {
		return *m.XferPort
	}
	return 0
}

func (m *DatanodeIDProto) GetInfoPort() uint32 {
	if m != nil && m.InfoPort != nil {
		return *m.InfoPort
	}
	return 0
}

func (m *DatanodeIDProto) GetIpcPort() uint32 {
	if m != nil && m.IpcPort != nil {
		return *m.IpcPort
	}
	return 0
}

func (m *DatanodeIDProto) GetInfoSecurePort() uint32 {
	if m != nil && m.InfoSecurePort != nil {
		return *m.InfoSecurePort
	}
	return Default_DatanodeIDProto_InfoSecurePort
}

// *
// DatanodeInfo array
type DatanodeInfosProto struct {
	Datanodes        []*DatanodeInfoProto `protobuf:"bytes,1,rep,name=datanodes" json:"datanodes,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *DatanodeInfosProto) Reset()         { *m = DatanodeInfosProto{} }
func (m *DatanodeInfosProto) String() string { return proto.CompactTextString(m) }
func (*DatanodeInfosProto) ProtoMessage()    {}

func (m *DatanodeInfosProto) GetDatanodes() []*DatanodeInfoProto {
	if m != nil {
		return m.Datanodes
	}
	return nil
}

// *
// The status of a Datanode
type DatanodeInfoProto struct {
	Id               *DatanodeIDProto              `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Capacity         *uint64                       `protobuf:"varint,2,opt,name=capacity,def=0" json:"capacity,omitempty"`
	DfsUsed          *uint64                       `protobuf:"varint,3,opt,name=dfsUsed,def=0" json:"dfsUsed,omitempty"`
	Remaining        *uint64                       `protobuf:"varint,4,opt,name=remaining,def=0" json:"remaining,omitempty"`
	BlockPoolUsed    *uint64                       `protobuf:"varint,5,opt,name=blockPoolUsed,def=0" json:"blockPoolUsed,omitempty"`
	LastUpdate       *uint64                       `protobuf:"varint,6,opt,name=lastUpdate,def=0" json:"lastUpdate,omitempty"`
	XceiverCount     *uint32                       `protobuf:"varint,7,opt,name=xceiverCount,def=0" json:"xceiverCount,omitempty"`
	Location         *string                       `protobuf:"bytes,8,opt,name=location" json:"location,omitempty"`
	AdminState       *DatanodeInfoProto_AdminState `protobuf:"varint,10,opt,name=adminState,enum=hadoop.hdfs.DatanodeInfoProto_AdminState,def=0" json:"adminState,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *DatanodeInfoProto) Reset()         { *m = DatanodeInfoProto{} }
func (m *DatanodeInfoProto) String() string { return proto.CompactTextString(m) }
func (*DatanodeInfoProto) ProtoMessage()    {}

const Default_DatanodeInfoProto_Capacity uint64 = 0
const Default_DatanodeInfoProto_DfsUsed uint64 = 0
const Default_DatanodeInfoProto_Remaining uint64 = 0
const Default_DatanodeInfoProto_BlockPoolUsed uint64 = 0
const Default_DatanodeInfoProto_LastUpdate uint64 = 0
const Default_DatanodeInfoProto_XceiverCount uint32 = 0
const Default_DatanodeInfoProto_AdminState DatanodeInfoProto_AdminState = DatanodeInfoProto_NORMAL

func (m *DatanodeInfoProto) GetId() *DatanodeIDProto {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DatanodeInfoProto) GetCapacity() uint64 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return Default_DatanodeInfoProto_Capacity
}

func (m *DatanodeInfoProto) GetDfsUsed() uint64 {
	if m != nil && m.DfsUsed != nil {
		return *m.DfsUsed
	}
	return Default_DatanodeInfoProto_DfsUsed
}

func (m *DatanodeInfoProto) GetRemaining() uint64 {
	if m != nil && m.Remaining != nil {
		return *m.Remaining
	}
	return Default_DatanodeInfoProto_Remaining
}

func (m *DatanodeInfoProto) GetBlockPoolUsed() uint64 {
	if m != nil && m.BlockPoolUsed != nil {
		return *m.BlockPoolUsed
	}
	return Default_DatanodeInfoProto_BlockPoolUsed
}

func (m *DatanodeInfoProto) GetLastUpdate() uint64 {
	if m != nil && m.LastUpdate != nil {
		return *m.LastUpdate
	}
	return Default_DatanodeInfoProto_LastUpdate
}

func (m *DatanodeInfoProto) GetXceiverCount() uint32 {
	if m != nil && m.XceiverCount != nil {
		return *m.XceiverCount
	}
	return Default_DatanodeInfoProto_XceiverCount
}

func (m *DatanodeInfoProto) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *DatanodeInfoProto) GetAdminState() DatanodeInfoProto_AdminState {
	if m != nil && m.AdminState != nil {
		return *m.AdminState
	}
	return Default_DatanodeInfoProto_AdminState
}

// *
// Summary of a file or directory
type ContentSummaryProto struct {
	Length           *uint64 `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
	FileCount        *uint64 `protobuf:"varint,2,req,name=fileCount" json:"fileCount,omitempty"`
	DirectoryCount   *uint64 `protobuf:"varint,3,req,name=directoryCount" json:"directoryCount,omitempty"`
	Quota            *uint64 `protobuf:"varint,4,req,name=quota" json:"quota,omitempty"`
	SpaceConsumed    *uint64 `protobuf:"varint,5,req,name=spaceConsumed" json:"spaceConsumed,omitempty"`
	SpaceQuota       *uint64 `protobuf:"varint,6,req,name=spaceQuota" json:"spaceQuota,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContentSummaryProto) Reset()         { *m = ContentSummaryProto{} }
func (m *ContentSummaryProto) String() string { return proto.CompactTextString(m) }
func (*ContentSummaryProto) ProtoMessage()    {}

func (m *ContentSummaryProto) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ContentSummaryProto) GetFileCount() uint64 {
	if m != nil && m.FileCount != nil {
		return *m.FileCount
	}
	return 0
}

func (m *ContentSummaryProto) GetDirectoryCount() uint64 {
	if m != nil && m.DirectoryCount != nil {
		return *m.DirectoryCount
	}
	return 0
}

func (m *ContentSummaryProto) GetQuota() uint64 {
	if m != nil && m.Quota != nil {
		return *m.Quota
	}
	return 0
}

func (m *ContentSummaryProto) GetSpaceConsumed() uint64 {
	if m != nil && m.SpaceConsumed != nil {
		return *m.SpaceConsumed
	}
	return 0
}

func (m *ContentSummaryProto) GetSpaceQuota() uint64 {
	if m != nil && m.SpaceQuota != nil {
		return *m.SpaceQuota
	}
	return 0
}

// *
// Contains a list of paths corresponding to corrupt files and a cookie
// used for iterative calls to NameNode.listCorruptFileBlocks.
//
type CorruptFileBlocksProto struct {
	Files            []string `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	Cookie           *string  `protobuf:"bytes,2,req,name=cookie" json:"cookie,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CorruptFileBlocksProto) Reset()         { *m = CorruptFileBlocksProto{} }
func (m *CorruptFileBlocksProto) String() string { return proto.CompactTextString(m) }
func (*CorruptFileBlocksProto) ProtoMessage()    {}

func (m *CorruptFileBlocksProto) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *CorruptFileBlocksProto) GetCookie() string {
	if m != nil && m.Cookie != nil {
		return *m.Cookie
	}
	return ""
}

// *
// File or Directory permision - same spec as posix
type FsPermissionProto struct {
	Perm             *uint32 `protobuf:"varint,1,req,name=perm" json:"perm,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FsPermissionProto) Reset()         { *m = FsPermissionProto{} }
func (m *FsPermissionProto) String() string { return proto.CompactTextString(m) }
func (*FsPermissionProto) ProtoMessage()    {}

func (m *FsPermissionProto) GetPerm() uint32 {
	if m != nil && m.Perm != nil {
		return *m.Perm
	}
	return 0
}

// *
// A LocatedBlock gives information about a block and its location.
type LocatedBlockProto struct {
	B                *ExtendedBlockProto       `protobuf:"bytes,1,req,name=b" json:"b,omitempty"`
	Offset           *uint64                   `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	Locs             []*DatanodeInfoProto      `protobuf:"bytes,3,rep,name=locs" json:"locs,omitempty"`
	Corrupt          *bool                     `protobuf:"varint,4,req,name=corrupt" json:"corrupt,omitempty"`
	BlockToken       *hadoop_common.TokenProto `protobuf:"bytes,5,req,name=blockToken" json:"blockToken,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *LocatedBlockProto) Reset()         { *m = LocatedBlockProto{} }
func (m *LocatedBlockProto) String() string { return proto.CompactTextString(m) }
func (*LocatedBlockProto) ProtoMessage()    {}

func (m *LocatedBlockProto) GetB() *ExtendedBlockProto {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *LocatedBlockProto) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *LocatedBlockProto) GetLocs() []*DatanodeInfoProto {
	if m != nil {
		return m.Locs
	}
	return nil
}

func (m *LocatedBlockProto) GetCorrupt() bool {
	if m != nil && m.Corrupt != nil {
		return *m.Corrupt
	}
	return false
}

func (m *LocatedBlockProto) GetBlockToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.BlockToken
	}
	return nil
}

type DataEncryptionKeyProto struct {
	KeyId               *uint32 `protobuf:"varint,1,req,name=keyId" json:"keyId,omitempty"`
	BlockPoolId         *string `protobuf:"bytes,2,req,name=blockPoolId" json:"blockPoolId,omitempty"`
	Nonce               []byte  `protobuf:"bytes,3,req,name=nonce" json:"nonce,omitempty"`
	EncryptionKey       []byte  `protobuf:"bytes,4,req,name=encryptionKey" json:"encryptionKey,omitempty"`
	ExpiryDate          *uint64 `protobuf:"varint,5,req,name=expiryDate" json:"expiryDate,omitempty"`
	EncryptionAlgorithm *string `protobuf:"bytes,6,opt,name=encryptionAlgorithm" json:"encryptionAlgorithm,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *DataEncryptionKeyProto) Reset()         { *m = DataEncryptionKeyProto{} }
func (m *DataEncryptionKeyProto) String() string { return proto.CompactTextString(m) }
func (*DataEncryptionKeyProto) ProtoMessage()    {}

func (m *DataEncryptionKeyProto) GetKeyId() uint32 {
	if m != nil && m.KeyId != nil {
		return *m.KeyId
	}
	return 0
}

func (m *DataEncryptionKeyProto) GetBlockPoolId() string {
	if m != nil && m.BlockPoolId != nil {
		return *m.BlockPoolId
	}
	return ""
}

func (m *DataEncryptionKeyProto) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *DataEncryptionKeyProto) GetEncryptionKey() []byte {
	if m != nil {
		return m.EncryptionKey
	}
	return nil
}

func (m *DataEncryptionKeyProto) GetExpiryDate() uint64 {
	if m != nil && m.ExpiryDate != nil {
		return *m.ExpiryDate
	}
	return 0
}

func (m *DataEncryptionKeyProto) GetEncryptionAlgorithm() string {
	if m != nil && m.EncryptionAlgorithm != nil {
		return *m.EncryptionAlgorithm
	}
	return ""
}

// *
// A set of file blocks and their locations.
type LocatedBlocksProto struct {
	FileLength          *uint64              `protobuf:"varint,1,req,name=fileLength" json:"fileLength,omitempty"`
	Blocks              []*LocatedBlockProto `protobuf:"bytes,2,rep,name=blocks" json:"blocks,omitempty"`
	UnderConstruction   *bool                `protobuf:"varint,3,req,name=underConstruction" json:"underConstruction,omitempty"`
	LastBlock           *LocatedBlockProto   `protobuf:"bytes,4,opt,name=lastBlock" json:"lastBlock,omitempty"`
	IsLastBlockComplete *bool                `protobuf:"varint,5,req,name=isLastBlockComplete" json:"isLastBlockComplete,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *LocatedBlocksProto) Reset()         { *m = LocatedBlocksProto{} }
func (m *LocatedBlocksProto) String() string { return proto.CompactTextString(m) }
func (*LocatedBlocksProto) ProtoMessage()    {}

func (m *LocatedBlocksProto) GetFileLength() uint64 {
	if m != nil && m.FileLength != nil {
		return *m.FileLength
	}
	return 0
}

func (m *LocatedBlocksProto) GetBlocks() []*LocatedBlockProto {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *LocatedBlocksProto) GetUnderConstruction() bool {
	if m != nil && m.UnderConstruction != nil {
		return *m.UnderConstruction
	}
	return false
}

func (m *LocatedBlocksProto) GetLastBlock() *LocatedBlockProto {
	if m != nil {
		return m.LastBlock
	}
	return nil
}

func (m *LocatedBlocksProto) GetIsLastBlockComplete() bool {
	if m != nil && m.IsLastBlockComplete != nil {
		return *m.IsLastBlockComplete
	}
	return false
}

// *
// Status of a file, directory or symlink
// Optionally includes a file's block locations if requested by client on the rpc call.
type HdfsFileStatusProto struct {
	FileType         *HdfsFileStatusProto_FileType `protobuf:"varint,1,req,name=fileType,enum=hadoop.hdfs.HdfsFileStatusProto_FileType" json:"fileType,omitempty"`
	Path             []byte                        `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	Length           *uint64                       `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	Permission       *FsPermissionProto            `protobuf:"bytes,4,req,name=permission" json:"permission,omitempty"`
	Owner            *string                       `protobuf:"bytes,5,req,name=owner" json:"owner,omitempty"`
	Group            *string                       `protobuf:"bytes,6,req,name=group" json:"group,omitempty"`
	ModificationTime *uint64                       `protobuf:"varint,7,req,name=modification_time" json:"modification_time,omitempty"`
	AccessTime       *uint64                       `protobuf:"varint,8,req,name=access_time" json:"access_time,omitempty"`
	// Optional fields for symlink
	Symlink []byte `protobuf:"bytes,9,opt,name=symlink" json:"symlink,omitempty"`
	// Optional fields for file
	BlockReplication *uint32             `protobuf:"varint,10,opt,name=block_replication,def=0" json:"block_replication,omitempty"`
	Blocksize        *uint64             `protobuf:"varint,11,opt,name=blocksize,def=0" json:"blocksize,omitempty"`
	Locations        *LocatedBlocksProto `protobuf:"bytes,12,opt,name=locations" json:"locations,omitempty"`
	// Optional field for fileId
	FileId           *uint64 `protobuf:"varint,13,opt,name=fileId,def=0" json:"fileId,omitempty"`
	ChildrenNum      *int32  `protobuf:"varint,14,opt,name=childrenNum,def=-1" json:"childrenNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HdfsFileStatusProto) Reset()         { *m = HdfsFileStatusProto{} }
func (m *HdfsFileStatusProto) String() string { return proto.CompactTextString(m) }
func (*HdfsFileStatusProto) ProtoMessage()    {}

const Default_HdfsFileStatusProto_BlockReplication uint32 = 0
const Default_HdfsFileStatusProto_Blocksize uint64 = 0
const Default_HdfsFileStatusProto_FileId uint64 = 0
const Default_HdfsFileStatusProto_ChildrenNum int32 = -1

func (m *HdfsFileStatusProto) GetFileType() HdfsFileStatusProto_FileType {
	if m != nil && m.FileType != nil {
		return *m.FileType
	}
	return HdfsFileStatusProto_IS_DIR
}

func (m *HdfsFileStatusProto) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *HdfsFileStatusProto) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *HdfsFileStatusProto) GetPermission() *FsPermissionProto {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *HdfsFileStatusProto) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *HdfsFileStatusProto) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *HdfsFileStatusProto) GetModificationTime() uint64 {
	if m != nil && m.ModificationTime != nil {
		return *m.ModificationTime
	}
	return 0
}

func (m *HdfsFileStatusProto) GetAccessTime() uint64 {
	if m != nil && m.AccessTime != nil {
		return *m.AccessTime
	}
	return 0
}

func (m *HdfsFileStatusProto) GetSymlink() []byte {
	if m != nil {
		return m.Symlink
	}
	return nil
}

func (m *HdfsFileStatusProto) GetBlockReplication() uint32 {
	if m != nil && m.BlockReplication != nil {
		return *m.BlockReplication
	}
	return Default_HdfsFileStatusProto_BlockReplication
}

func (m *HdfsFileStatusProto) GetBlocksize() uint64 {
	if m != nil && m.Blocksize != nil {
		return *m.Blocksize
	}
	return Default_HdfsFileStatusProto_Blocksize
}

func (m *HdfsFileStatusProto) GetLocations() *LocatedBlocksProto {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *HdfsFileStatusProto) GetFileId() uint64 {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return Default_HdfsFileStatusProto_FileId
}

func (m *HdfsFileStatusProto) GetChildrenNum() int32 {
	if m != nil && m.ChildrenNum != nil {
		return *m.ChildrenNum
	}
	return Default_HdfsFileStatusProto_ChildrenNum
}

// *
// HDFS Server Defaults
type FsServerDefaultsProto struct {
	BlockSize           *uint64            `protobuf:"varint,1,req,name=blockSize" json:"blockSize,omitempty"`
	BytesPerChecksum    *uint32            `protobuf:"varint,2,req,name=bytesPerChecksum" json:"bytesPerChecksum,omitempty"`
	WritePacketSize     *uint32            `protobuf:"varint,3,req,name=writePacketSize" json:"writePacketSize,omitempty"`
	Replication         *uint32            `protobuf:"varint,4,req,name=replication" json:"replication,omitempty"`
	FileBufferSize      *uint32            `protobuf:"varint,5,req,name=fileBufferSize" json:"fileBufferSize,omitempty"`
	EncryptDataTransfer *bool              `protobuf:"varint,6,opt,name=encryptDataTransfer,def=0" json:"encryptDataTransfer,omitempty"`
	TrashInterval       *uint64            `protobuf:"varint,7,opt,name=trashInterval,def=0" json:"trashInterval,omitempty"`
	ChecksumType        *ChecksumTypeProto `protobuf:"varint,8,opt,name=checksumType,enum=hadoop.hdfs.ChecksumTypeProto,def=1" json:"checksumType,omitempty"`
	XXX_unrecognized    []byte             `json:"-"`
}

func (m *FsServerDefaultsProto) Reset()         { *m = FsServerDefaultsProto{} }
func (m *FsServerDefaultsProto) String() string { return proto.CompactTextString(m) }
func (*FsServerDefaultsProto) ProtoMessage()    {}

const Default_FsServerDefaultsProto_EncryptDataTransfer bool = false
const Default_FsServerDefaultsProto_TrashInterval uint64 = 0
const Default_FsServerDefaultsProto_ChecksumType ChecksumTypeProto = ChecksumTypeProto_CHECKSUM_CRC32

func (m *FsServerDefaultsProto) GetBlockSize() uint64 {
	if m != nil && m.BlockSize != nil {
		return *m.BlockSize
	}
	return 0
}

func (m *FsServerDefaultsProto) GetBytesPerChecksum() uint32 {
	if m != nil && m.BytesPerChecksum != nil {
		return *m.BytesPerChecksum
	}
	return 0
}

func (m *FsServerDefaultsProto) GetWritePacketSize() uint32 {
	if m != nil && m.WritePacketSize != nil {
		return *m.WritePacketSize
	}
	return 0
}

func (m *FsServerDefaultsProto) GetReplication() uint32 {
	if m != nil && m.Replication != nil {
		return *m.Replication
	}
	return 0
}

func (m *FsServerDefaultsProto) GetFileBufferSize() uint32 {
	if m != nil && m.FileBufferSize != nil {
		return *m.FileBufferSize
	}
	return 0
}

func (m *FsServerDefaultsProto) GetEncryptDataTransfer() bool {
	if m != nil && m.EncryptDataTransfer != nil {
		return *m.EncryptDataTransfer
	}
	return Default_FsServerDefaultsProto_EncryptDataTransfer
}

func (m *FsServerDefaultsProto) GetTrashInterval() uint64 {
	if m != nil && m.TrashInterval != nil {
		return *m.TrashInterval
	}
	return Default_FsServerDefaultsProto_TrashInterval
}

func (m *FsServerDefaultsProto) GetChecksumType() ChecksumTypeProto {
	if m != nil && m.ChecksumType != nil {
		return *m.ChecksumType
	}
	return Default_FsServerDefaultsProto_ChecksumType
}

// *
// Directory listing
type DirectoryListingProto struct {
	PartialListing   []*HdfsFileStatusProto `protobuf:"bytes,1,rep,name=partialListing" json:"partialListing,omitempty"`
	RemainingEntries *uint32                `protobuf:"varint,2,req,name=remainingEntries" json:"remainingEntries,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *DirectoryListingProto) Reset()         { *m = DirectoryListingProto{} }
func (m *DirectoryListingProto) String() string { return proto.CompactTextString(m) }
func (*DirectoryListingProto) ProtoMessage()    {}

func (m *DirectoryListingProto) GetPartialListing() []*HdfsFileStatusProto {
	if m != nil {
		return m.PartialListing
	}
	return nil
}

func (m *DirectoryListingProto) GetRemainingEntries() uint32 {
	if m != nil && m.RemainingEntries != nil {
		return *m.RemainingEntries
	}
	return 0
}

// *
// Status of a snapshottable directory: besides the normal information for
// a directory status, also include snapshot quota, number of snapshots, and
// the full path of the parent directory.
type SnapshottableDirectoryStatusProto struct {
	DirStatus *HdfsFileStatusProto `protobuf:"bytes,1,req,name=dirStatus" json:"dirStatus,omitempty"`
	// Fields specific for snapshottable directory
	SnapshotQuota    *uint32 `protobuf:"varint,2,req,name=snapshot_quota" json:"snapshot_quota,omitempty"`
	SnapshotNumber   *uint32 `protobuf:"varint,3,req,name=snapshot_number" json:"snapshot_number,omitempty"`
	ParentFullpath   []byte  `protobuf:"bytes,4,req,name=parent_fullpath" json:"parent_fullpath,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SnapshottableDirectoryStatusProto) Reset()         { *m = SnapshottableDirectoryStatusProto{} }
func (m *SnapshottableDirectoryStatusProto) String() string { return proto.CompactTextString(m) }
func (*SnapshottableDirectoryStatusProto) ProtoMessage()    {}

func (m *SnapshottableDirectoryStatusProto) GetDirStatus() *HdfsFileStatusProto {
	if m != nil {
		return m.DirStatus
	}
	return nil
}

func (m *SnapshottableDirectoryStatusProto) GetSnapshotQuota() uint32 {
	if m != nil && m.SnapshotQuota != nil {
		return *m.SnapshotQuota
	}
	return 0
}

func (m *SnapshottableDirectoryStatusProto) GetSnapshotNumber() uint32 {
	if m != nil && m.SnapshotNumber != nil {
		return *m.SnapshotNumber
	}
	return 0
}

func (m *SnapshottableDirectoryStatusProto) GetParentFullpath() []byte {
	if m != nil {
		return m.ParentFullpath
	}
	return nil
}

// *
// Snapshottable directory listing
type SnapshottableDirectoryListingProto struct {
	SnapshottableDirListing []*SnapshottableDirectoryStatusProto `protobuf:"bytes,1,rep,name=snapshottableDirListing" json:"snapshottableDirListing,omitempty"`
	XXX_unrecognized        []byte                               `json:"-"`
}

func (m *SnapshottableDirectoryListingProto) Reset()         { *m = SnapshottableDirectoryListingProto{} }
func (m *SnapshottableDirectoryListingProto) String() string { return proto.CompactTextString(m) }
func (*SnapshottableDirectoryListingProto) ProtoMessage()    {}

func (m *SnapshottableDirectoryListingProto) GetSnapshottableDirListing() []*SnapshottableDirectoryStatusProto {
	if m != nil {
		return m.SnapshottableDirListing
	}
	return nil
}

// *
// Snapshot diff report entry
type SnapshotDiffReportEntryProto struct {
	Fullpath          []byte  `protobuf:"bytes,1,req,name=fullpath" json:"fullpath,omitempty"`
	ModificationLabel *string `protobuf:"bytes,2,req,name=modificationLabel" json:"modificationLabel,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *SnapshotDiffReportEntryProto) Reset()         { *m = SnapshotDiffReportEntryProto{} }
func (m *SnapshotDiffReportEntryProto) String() string { return proto.CompactTextString(m) }
func (*SnapshotDiffReportEntryProto) ProtoMessage()    {}

func (m *SnapshotDiffReportEntryProto) GetFullpath() []byte {
	if m != nil {
		return m.Fullpath
	}
	return nil
}

func (m *SnapshotDiffReportEntryProto) GetModificationLabel() string {
	if m != nil && m.ModificationLabel != nil {
		return *m.ModificationLabel
	}
	return ""
}

// *
// Snapshot diff report
type SnapshotDiffReportProto struct {
	// full path of the directory where snapshots were taken
	SnapshotRoot      *string                         `protobuf:"bytes,1,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	FromSnapshot      *string                         `protobuf:"bytes,2,req,name=fromSnapshot" json:"fromSnapshot,omitempty"`
	ToSnapshot        *string                         `protobuf:"bytes,3,req,name=toSnapshot" json:"toSnapshot,omitempty"`
	DiffReportEntries []*SnapshotDiffReportEntryProto `protobuf:"bytes,4,rep,name=diffReportEntries" json:"diffReportEntries,omitempty"`
	XXX_unrecognized  []byte                          `json:"-"`
}

func (m *SnapshotDiffReportProto) Reset()         { *m = SnapshotDiffReportProto{} }
func (m *SnapshotDiffReportProto) String() string { return proto.CompactTextString(m) }
func (*SnapshotDiffReportProto) ProtoMessage()    {}

func (m *SnapshotDiffReportProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *SnapshotDiffReportProto) GetFromSnapshot() string {
	if m != nil && m.FromSnapshot != nil {
		return *m.FromSnapshot
	}
	return ""
}

func (m *SnapshotDiffReportProto) GetToSnapshot() string {
	if m != nil && m.ToSnapshot != nil {
		return *m.ToSnapshot
	}
	return ""
}

func (m *SnapshotDiffReportProto) GetDiffReportEntries() []*SnapshotDiffReportEntryProto {
	if m != nil {
		return m.DiffReportEntries
	}
	return nil
}

// *
// Common node information shared by all the nodes in the cluster
type StorageInfoProto struct {
	LayoutVersion    *uint32 `protobuf:"varint,1,req,name=layoutVersion" json:"layoutVersion,omitempty"`
	NamespceID       *uint32 `protobuf:"varint,2,req,name=namespceID" json:"namespceID,omitempty"`
	ClusterID        *string `protobuf:"bytes,3,req,name=clusterID" json:"clusterID,omitempty"`
	CTime            *uint64 `protobuf:"varint,4,req,name=cTime" json:"cTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StorageInfoProto) Reset()         { *m = StorageInfoProto{} }
func (m *StorageInfoProto) String() string { return proto.CompactTextString(m) }
func (*StorageInfoProto) ProtoMessage()    {}

func (m *StorageInfoProto) GetLayoutVersion() uint32 {
	if m != nil && m.LayoutVersion != nil {
		return *m.LayoutVersion
	}
	return 0
}

func (m *StorageInfoProto) GetNamespceID() uint32 {
	if m != nil && m.NamespceID != nil {
		return *m.NamespceID
	}
	return 0
}

func (m *StorageInfoProto) GetClusterID() string {
	if m != nil && m.ClusterID != nil {
		return *m.ClusterID
	}
	return ""
}

func (m *StorageInfoProto) GetCTime() uint64 {
	if m != nil && m.CTime != nil {
		return *m.CTime
	}
	return 0
}

// *
// Information sent by a namenode to identify itself to the primary namenode.
type NamenodeRegistrationProto struct {
	RpcAddress       *string                                      `protobuf:"bytes,1,req,name=rpcAddress" json:"rpcAddress,omitempty"`
	HttpAddress      *string                                      `protobuf:"bytes,2,req,name=httpAddress" json:"httpAddress,omitempty"`
	StorageInfo      *StorageInfoProto                            `protobuf:"bytes,3,req,name=storageInfo" json:"storageInfo,omitempty"`
	Role             *NamenodeRegistrationProto_NamenodeRoleProto `protobuf:"varint,4,opt,name=role,enum=hadoop.hdfs.NamenodeRegistrationProto_NamenodeRoleProto,def=1" json:"role,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *NamenodeRegistrationProto) Reset()         { *m = NamenodeRegistrationProto{} }
func (m *NamenodeRegistrationProto) String() string { return proto.CompactTextString(m) }
func (*NamenodeRegistrationProto) ProtoMessage()    {}

const Default_NamenodeRegistrationProto_Role NamenodeRegistrationProto_NamenodeRoleProto = NamenodeRegistrationProto_NAMENODE

func (m *NamenodeRegistrationProto) GetRpcAddress() string {
	if m != nil && m.RpcAddress != nil {
		return *m.RpcAddress
	}
	return ""
}

func (m *NamenodeRegistrationProto) GetHttpAddress() string {
	if m != nil && m.HttpAddress != nil {
		return *m.HttpAddress
	}
	return ""
}

func (m *NamenodeRegistrationProto) GetStorageInfo() *StorageInfoProto {
	if m != nil {
		return m.StorageInfo
	}
	return nil
}

func (m *NamenodeRegistrationProto) GetRole() NamenodeRegistrationProto_NamenodeRoleProto {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return Default_NamenodeRegistrationProto_Role
}

// *
// Unique signature to identify checkpoint transactions.
type CheckpointSignatureProto struct {
	BlockPoolId              *string           `protobuf:"bytes,1,req,name=blockPoolId" json:"blockPoolId,omitempty"`
	MostRecentCheckpointTxId *uint64           `protobuf:"varint,2,req,name=mostRecentCheckpointTxId" json:"mostRecentCheckpointTxId,omitempty"`
	CurSegmentTxId           *uint64           `protobuf:"varint,3,req,name=curSegmentTxId" json:"curSegmentTxId,omitempty"`
	StorageInfo              *StorageInfoProto `protobuf:"bytes,4,req,name=storageInfo" json:"storageInfo,omitempty"`
	XXX_unrecognized         []byte            `json:"-"`
}

func (m *CheckpointSignatureProto) Reset()         { *m = CheckpointSignatureProto{} }
func (m *CheckpointSignatureProto) String() string { return proto.CompactTextString(m) }
func (*CheckpointSignatureProto) ProtoMessage()    {}

func (m *CheckpointSignatureProto) GetBlockPoolId() string {
	if m != nil && m.BlockPoolId != nil {
		return *m.BlockPoolId
	}
	return ""
}

func (m *CheckpointSignatureProto) GetMostRecentCheckpointTxId() uint64 {
	if m != nil && m.MostRecentCheckpointTxId != nil {
		return *m.MostRecentCheckpointTxId
	}
	return 0
}

func (m *CheckpointSignatureProto) GetCurSegmentTxId() uint64 {
	if m != nil && m.CurSegmentTxId != nil {
		return *m.CurSegmentTxId
	}
	return 0
}

func (m *CheckpointSignatureProto) GetStorageInfo() *StorageInfoProto {
	if m != nil {
		return m.StorageInfo
	}
	return nil
}

// *
// Command sent from one namenode to another namenode.
type NamenodeCommandProto struct {
	Action           *uint32                    `protobuf:"varint,1,req,name=action" json:"action,omitempty"`
	Type             *NamenodeCommandProto_Type `protobuf:"varint,2,req,name=type,enum=hadoop.hdfs.NamenodeCommandProto_Type" json:"type,omitempty"`
	CheckpointCmd    *CheckpointCommandProto    `protobuf:"bytes,3,opt,name=checkpointCmd" json:"checkpointCmd,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *NamenodeCommandProto) Reset()         { *m = NamenodeCommandProto{} }
func (m *NamenodeCommandProto) String() string { return proto.CompactTextString(m) }
func (*NamenodeCommandProto) ProtoMessage()    {}

func (m *NamenodeCommandProto) GetAction() uint32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *NamenodeCommandProto) GetType() NamenodeCommandProto_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return NamenodeCommandProto_NamenodeCommand
}

func (m *NamenodeCommandProto) GetCheckpointCmd() *CheckpointCommandProto {
	if m != nil {
		return m.CheckpointCmd
	}
	return nil
}

// *
// Command returned from primary to checkpointing namenode.
// This command has checkpoint signature that identifies
// checkpoint transaction and is needed for further
// communication related to checkpointing.
type CheckpointCommandProto struct {
	// Unique signature to identify checkpoint transation
	Signature *CheckpointSignatureProto `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	// If true, return transfer image to primary upon the completion of checkpoint
	NeedToReturnImage *bool  `protobuf:"varint,2,req,name=needToReturnImage" json:"needToReturnImage,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *CheckpointCommandProto) Reset()         { *m = CheckpointCommandProto{} }
func (m *CheckpointCommandProto) String() string { return proto.CompactTextString(m) }
func (*CheckpointCommandProto) ProtoMessage()    {}

func (m *CheckpointCommandProto) GetSignature() *CheckpointSignatureProto {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *CheckpointCommandProto) GetNeedToReturnImage() bool {
	if m != nil && m.NeedToReturnImage != nil {
		return *m.NeedToReturnImage
	}
	return false
}

// *
// Block information
type BlockProto struct {
	BlockId          *uint64 `protobuf:"varint,1,req,name=blockId" json:"blockId,omitempty"`
	GenStamp         *uint64 `protobuf:"varint,2,req,name=genStamp" json:"genStamp,omitempty"`
	NumBytes         *uint64 `protobuf:"varint,3,opt,name=numBytes,def=0" json:"numBytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlockProto) Reset()         { *m = BlockProto{} }
func (m *BlockProto) String() string { return proto.CompactTextString(m) }
func (*BlockProto) ProtoMessage()    {}

const Default_BlockProto_NumBytes uint64 = 0

func (m *BlockProto) GetBlockId() uint64 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *BlockProto) GetGenStamp() uint64 {
	if m != nil && m.GenStamp != nil {
		return *m.GenStamp
	}
	return 0
}

func (m *BlockProto) GetNumBytes() uint64 {
	if m != nil && m.NumBytes != nil {
		return *m.NumBytes
	}
	return Default_BlockProto_NumBytes
}

// *
// Block and datanodes where is it located
type BlockWithLocationsProto struct {
	Block            *BlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	StorageIDs       []string    `protobuf:"bytes,2,rep,name=storageIDs" json:"storageIDs,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *BlockWithLocationsProto) Reset()         { *m = BlockWithLocationsProto{} }
func (m *BlockWithLocationsProto) String() string { return proto.CompactTextString(m) }
func (*BlockWithLocationsProto) ProtoMessage()    {}

func (m *BlockWithLocationsProto) GetBlock() *BlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockWithLocationsProto) GetStorageIDs() []string {
	if m != nil {
		return m.StorageIDs
	}
	return nil
}

// *
// List of block with locations
type BlocksWithLocationsProto struct {
	Blocks           []*BlockWithLocationsProto `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *BlocksWithLocationsProto) Reset()         { *m = BlocksWithLocationsProto{} }
func (m *BlocksWithLocationsProto) String() string { return proto.CompactTextString(m) }
func (*BlocksWithLocationsProto) ProtoMessage()    {}

func (m *BlocksWithLocationsProto) GetBlocks() []*BlockWithLocationsProto {
	if m != nil {
		return m.Blocks
	}
	return nil
}

// *
// Editlog information with available transactions
type RemoteEditLogProto struct {
	StartTxId        *uint64 `protobuf:"varint,1,req,name=startTxId" json:"startTxId,omitempty"`
	EndTxId          *uint64 `protobuf:"varint,2,req,name=endTxId" json:"endTxId,omitempty"`
	IsInProgress     *bool   `protobuf:"varint,3,opt,name=isInProgress,def=0" json:"isInProgress,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoteEditLogProto) Reset()         { *m = RemoteEditLogProto{} }
func (m *RemoteEditLogProto) String() string { return proto.CompactTextString(m) }
func (*RemoteEditLogProto) ProtoMessage()    {}

const Default_RemoteEditLogProto_IsInProgress bool = false

func (m *RemoteEditLogProto) GetStartTxId() uint64 {
	if m != nil && m.StartTxId != nil {
		return *m.StartTxId
	}
	return 0
}

func (m *RemoteEditLogProto) GetEndTxId() uint64 {
	if m != nil && m.EndTxId != nil {
		return *m.EndTxId
	}
	return 0
}

func (m *RemoteEditLogProto) GetIsInProgress() bool {
	if m != nil && m.IsInProgress != nil {
		return *m.IsInProgress
	}
	return Default_RemoteEditLogProto_IsInProgress
}

// *
// Enumeration of editlogs available on a remote namenode
type RemoteEditLogManifestProto struct {
	Logs             []*RemoteEditLogProto `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *RemoteEditLogManifestProto) Reset()         { *m = RemoteEditLogManifestProto{} }
func (m *RemoteEditLogManifestProto) String() string { return proto.CompactTextString(m) }
func (*RemoteEditLogManifestProto) ProtoMessage()    {}

func (m *RemoteEditLogManifestProto) GetLogs() []*RemoteEditLogProto {
	if m != nil {
		return m.Logs
	}
	return nil
}

// *
// Namespace information that describes namespace on a namenode
type NamespaceInfoProto struct {
	BuildVersion     *string           `protobuf:"bytes,1,req,name=buildVersion" json:"buildVersion,omitempty"`
	Unused           *uint32           `protobuf:"varint,2,req,name=unused" json:"unused,omitempty"`
	BlockPoolID      *string           `protobuf:"bytes,3,req,name=blockPoolID" json:"blockPoolID,omitempty"`
	StorageInfo      *StorageInfoProto `protobuf:"bytes,4,req,name=storageInfo" json:"storageInfo,omitempty"`
	SoftwareVersion  *string           `protobuf:"bytes,5,req,name=softwareVersion" json:"softwareVersion,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NamespaceInfoProto) Reset()         { *m = NamespaceInfoProto{} }
func (m *NamespaceInfoProto) String() string { return proto.CompactTextString(m) }
func (*NamespaceInfoProto) ProtoMessage()    {}

func (m *NamespaceInfoProto) GetBuildVersion() string {
	if m != nil && m.BuildVersion != nil {
		return *m.BuildVersion
	}
	return ""
}

func (m *NamespaceInfoProto) GetUnused() uint32 {
	if m != nil && m.Unused != nil {
		return *m.Unused
	}
	return 0
}

func (m *NamespaceInfoProto) GetBlockPoolID() string {
	if m != nil && m.BlockPoolID != nil {
		return *m.BlockPoolID
	}
	return ""
}

func (m *NamespaceInfoProto) GetStorageInfo() *StorageInfoProto {
	if m != nil {
		return m.StorageInfo
	}
	return nil
}

func (m *NamespaceInfoProto) GetSoftwareVersion() string {
	if m != nil && m.SoftwareVersion != nil {
		return *m.SoftwareVersion
	}
	return ""
}

// *
// Block access token information
type BlockKeyProto struct {
	KeyId            *uint32 `protobuf:"varint,1,req,name=keyId" json:"keyId,omitempty"`
	ExpiryDate       *uint64 `protobuf:"varint,2,req,name=expiryDate" json:"expiryDate,omitempty"`
	KeyBytes         []byte  `protobuf:"bytes,3,opt,name=keyBytes" json:"keyBytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlockKeyProto) Reset()         { *m = BlockKeyProto{} }
func (m *BlockKeyProto) String() string { return proto.CompactTextString(m) }
func (*BlockKeyProto) ProtoMessage()    {}

func (m *BlockKeyProto) GetKeyId() uint32 {
	if m != nil && m.KeyId != nil {
		return *m.KeyId
	}
	return 0
}

func (m *BlockKeyProto) GetExpiryDate() uint64 {
	if m != nil && m.ExpiryDate != nil {
		return *m.ExpiryDate
	}
	return 0
}

func (m *BlockKeyProto) GetKeyBytes() []byte {
	if m != nil {
		return m.KeyBytes
	}
	return nil
}

// *
// Current key and set of block keys at the namenode.
type ExportedBlockKeysProto struct {
	IsBlockTokenEnabled *bool            `protobuf:"varint,1,req,name=isBlockTokenEnabled" json:"isBlockTokenEnabled,omitempty"`
	KeyUpdateInterval   *uint64          `protobuf:"varint,2,req,name=keyUpdateInterval" json:"keyUpdateInterval,omitempty"`
	TokenLifeTime       *uint64          `protobuf:"varint,3,req,name=tokenLifeTime" json:"tokenLifeTime,omitempty"`
	CurrentKey          *BlockKeyProto   `protobuf:"bytes,4,req,name=currentKey" json:"currentKey,omitempty"`
	AllKeys             []*BlockKeyProto `protobuf:"bytes,5,rep,name=allKeys" json:"allKeys,omitempty"`
	XXX_unrecognized    []byte           `json:"-"`
}

func (m *ExportedBlockKeysProto) Reset()         { *m = ExportedBlockKeysProto{} }
func (m *ExportedBlockKeysProto) String() string { return proto.CompactTextString(m) }
func (*ExportedBlockKeysProto) ProtoMessage()    {}

func (m *ExportedBlockKeysProto) GetIsBlockTokenEnabled() bool {
	if m != nil && m.IsBlockTokenEnabled != nil {
		return *m.IsBlockTokenEnabled
	}
	return false
}

func (m *ExportedBlockKeysProto) GetKeyUpdateInterval() uint64 {
	if m != nil && m.KeyUpdateInterval != nil {
		return *m.KeyUpdateInterval
	}
	return 0
}

func (m *ExportedBlockKeysProto) GetTokenLifeTime() uint64 {
	if m != nil && m.TokenLifeTime != nil {
		return *m.TokenLifeTime
	}
	return 0
}

func (m *ExportedBlockKeysProto) GetCurrentKey() *BlockKeyProto {
	if m != nil {
		return m.CurrentKey
	}
	return nil
}

func (m *ExportedBlockKeysProto) GetAllKeys() []*BlockKeyProto {
	if m != nil {
		return m.AllKeys
	}
	return nil
}

// *
// Block that needs to be recovered with at a given location
type RecoveringBlockProto struct {
	NewGenStamp      *uint64            `protobuf:"varint,1,req,name=newGenStamp" json:"newGenStamp,omitempty"`
	Block            *LocatedBlockProto `protobuf:"bytes,2,req,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RecoveringBlockProto) Reset()         { *m = RecoveringBlockProto{} }
func (m *RecoveringBlockProto) String() string { return proto.CompactTextString(m) }
func (*RecoveringBlockProto) ProtoMessage()    {}

func (m *RecoveringBlockProto) GetNewGenStamp() uint64 {
	if m != nil && m.NewGenStamp != nil {
		return *m.NewGenStamp
	}
	return 0
}

func (m *RecoveringBlockProto) GetBlock() *LocatedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

// *
// void request
type VersionRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *VersionRequestProto) Reset()         { *m = VersionRequestProto{} }
func (m *VersionRequestProto) String() string { return proto.CompactTextString(m) }
func (*VersionRequestProto) ProtoMessage()    {}

// *
// Version response from namenode.
type VersionResponseProto struct {
	Info             *NamespaceInfoProto `protobuf:"bytes,1,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *VersionResponseProto) Reset()         { *m = VersionResponseProto{} }
func (m *VersionResponseProto) String() string { return proto.CompactTextString(m) }
func (*VersionResponseProto) ProtoMessage()    {}

func (m *VersionResponseProto) GetInfo() *NamespaceInfoProto {
	if m != nil {
		return m.Info
	}
	return nil
}

// *
// Information related to a snapshot
// TODO: add more information
type SnapshotInfoProto struct {
	SnapshotName     *string            `protobuf:"bytes,1,req,name=snapshotName" json:"snapshotName,omitempty"`
	SnapshotRoot     *string            `protobuf:"bytes,2,req,name=snapshotRoot" json:"snapshotRoot,omitempty"`
	Permission       *FsPermissionProto `protobuf:"bytes,3,req,name=permission" json:"permission,omitempty"`
	Owner            *string            `protobuf:"bytes,4,req,name=owner" json:"owner,omitempty"`
	Group            *string            `protobuf:"bytes,5,req,name=group" json:"group,omitempty"`
	CreateTime       *string            `protobuf:"bytes,6,req,name=createTime" json:"createTime,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SnapshotInfoProto) Reset()         { *m = SnapshotInfoProto{} }
func (m *SnapshotInfoProto) String() string { return proto.CompactTextString(m) }
func (*SnapshotInfoProto) ProtoMessage()    {}

func (m *SnapshotInfoProto) GetSnapshotName() string {
	if m != nil && m.SnapshotName != nil {
		return *m.SnapshotName
	}
	return ""
}

func (m *SnapshotInfoProto) GetSnapshotRoot() string {
	if m != nil && m.SnapshotRoot != nil {
		return *m.SnapshotRoot
	}
	return ""
}

func (m *SnapshotInfoProto) GetPermission() *FsPermissionProto {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *SnapshotInfoProto) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *SnapshotInfoProto) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *SnapshotInfoProto) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterEnum("hadoop.hdfs.ChecksumTypeProto", ChecksumTypeProto_name, ChecksumTypeProto_value)
	proto.RegisterEnum("hadoop.hdfs.ReplicaStateProto", ReplicaStateProto_name, ReplicaStateProto_value)
	proto.RegisterEnum("hadoop.hdfs.DatanodeInfoProto_AdminState", DatanodeInfoProto_AdminState_name, DatanodeInfoProto_AdminState_value)
	proto.RegisterEnum("hadoop.hdfs.HdfsFileStatusProto_FileType", HdfsFileStatusProto_FileType_name, HdfsFileStatusProto_FileType_value)
	proto.RegisterEnum("hadoop.hdfs.NamenodeRegistrationProto_NamenodeRoleProto", NamenodeRegistrationProto_NamenodeRoleProto_name, NamenodeRegistrationProto_NamenodeRoleProto_value)
	proto.RegisterEnum("hadoop.hdfs.NamenodeCommandProto_Type", NamenodeCommandProto_Type_name, NamenodeCommandProto_Type_value)
}
