// Code generated by protoc-gen-go.
// source: xattr.proto
// DO NOT EDIT!

package hadoop_hdfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type XAttrSetFlagProto int32

const (
	XAttrSetFlagProto_XATTR_CREATE  XAttrSetFlagProto = 1
	XAttrSetFlagProto_XATTR_REPLACE XAttrSetFlagProto = 2
)

var XAttrSetFlagProto_name = map[int32]string{
	1: "XATTR_CREATE",
	2: "XATTR_REPLACE",
}
var XAttrSetFlagProto_value = map[string]int32{
	"XATTR_CREATE":  1,
	"XATTR_REPLACE": 2,
}

func (x XAttrSetFlagProto) Enum() *XAttrSetFlagProto {
	p := new(XAttrSetFlagProto)
	*p = x
	return p
}
func (x XAttrSetFlagProto) String() string {
	return proto.EnumName(XAttrSetFlagProto_name, int32(x))
}
func (x *XAttrSetFlagProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(XAttrSetFlagProto_value, data, "XAttrSetFlagProto")
	if err != nil {
		return err
	}
	*x = XAttrSetFlagProto(value)
	return nil
}
func (XAttrSetFlagProto) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type XAttrProto_XAttrNamespaceProto int32

const (
	XAttrProto_USER     XAttrProto_XAttrNamespaceProto = 0
	XAttrProto_TRUSTED  XAttrProto_XAttrNamespaceProto = 1
	XAttrProto_SECURITY XAttrProto_XAttrNamespaceProto = 2
	XAttrProto_SYSTEM   XAttrProto_XAttrNamespaceProto = 3
	XAttrProto_RAW      XAttrProto_XAttrNamespaceProto = 4
)

var XAttrProto_XAttrNamespaceProto_name = map[int32]string{
	0: "USER",
	1: "TRUSTED",
	2: "SECURITY",
	3: "SYSTEM",
	4: "RAW",
}
var XAttrProto_XAttrNamespaceProto_value = map[string]int32{
	"USER":     0,
	"TRUSTED":  1,
	"SECURITY": 2,
	"SYSTEM":   3,
	"RAW":      4,
}

func (x XAttrProto_XAttrNamespaceProto) Enum() *XAttrProto_XAttrNamespaceProto {
	p := new(XAttrProto_XAttrNamespaceProto)
	*p = x
	return p
}
func (x XAttrProto_XAttrNamespaceProto) String() string {
	return proto.EnumName(XAttrProto_XAttrNamespaceProto_name, int32(x))
}
func (x *XAttrProto_XAttrNamespaceProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(XAttrProto_XAttrNamespaceProto_value, data, "XAttrProto_XAttrNamespaceProto")
	if err != nil {
		return err
	}
	*x = XAttrProto_XAttrNamespaceProto(value)
	return nil
}
func (XAttrProto_XAttrNamespaceProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 0}
}

type XAttrProto struct {
	Namespace        *XAttrProto_XAttrNamespaceProto `protobuf:"varint,1,req,name=namespace,enum=hadoop.hdfs.XAttrProto_XAttrNamespaceProto" json:"namespace,omitempty"`
	Name             *string                         `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Value            []byte                          `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *XAttrProto) Reset()                    { *m = XAttrProto{} }
func (m *XAttrProto) String() string            { return proto.CompactTextString(m) }
func (*XAttrProto) ProtoMessage()               {}
func (*XAttrProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *XAttrProto) GetNamespace() XAttrProto_XAttrNamespaceProto {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return XAttrProto_USER
}

func (m *XAttrProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *XAttrProto) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type XAttrEditLogProto struct {
	Src              *string       `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	XAttrs           []*XAttrProto `protobuf:"bytes,2,rep,name=xAttrs" json:"xAttrs,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *XAttrEditLogProto) Reset()                    { *m = XAttrEditLogProto{} }
func (m *XAttrEditLogProto) String() string            { return proto.CompactTextString(m) }
func (*XAttrEditLogProto) ProtoMessage()               {}
func (*XAttrEditLogProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *XAttrEditLogProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *XAttrEditLogProto) GetXAttrs() []*XAttrProto {
	if m != nil {
		return m.XAttrs
	}
	return nil
}

type SetXAttrRequestProto struct {
	Src              *string     `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XAttr            *XAttrProto `protobuf:"bytes,2,opt,name=xAttr" json:"xAttr,omitempty"`
	Flag             *uint32     `protobuf:"varint,3,opt,name=flag" json:"flag,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SetXAttrRequestProto) Reset()                    { *m = SetXAttrRequestProto{} }
func (m *SetXAttrRequestProto) String() string            { return proto.CompactTextString(m) }
func (*SetXAttrRequestProto) ProtoMessage()               {}
func (*SetXAttrRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *SetXAttrRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetXAttrRequestProto) GetXAttr() *XAttrProto {
	if m != nil {
		return m.XAttr
	}
	return nil
}

func (m *SetXAttrRequestProto) GetFlag() uint32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

type SetXAttrResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetXAttrResponseProto) Reset()                    { *m = SetXAttrResponseProto{} }
func (m *SetXAttrResponseProto) String() string            { return proto.CompactTextString(m) }
func (*SetXAttrResponseProto) ProtoMessage()               {}
func (*SetXAttrResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

type GetXAttrsRequestProto struct {
	Src              *string       `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XAttrs           []*XAttrProto `protobuf:"bytes,2,rep,name=xAttrs" json:"xAttrs,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GetXAttrsRequestProto) Reset()                    { *m = GetXAttrsRequestProto{} }
func (m *GetXAttrsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetXAttrsRequestProto) ProtoMessage()               {}
func (*GetXAttrsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *GetXAttrsRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *GetXAttrsRequestProto) GetXAttrs() []*XAttrProto {
	if m != nil {
		return m.XAttrs
	}
	return nil
}

type GetXAttrsResponseProto struct {
	XAttrs           []*XAttrProto `protobuf:"bytes,1,rep,name=xAttrs" json:"xAttrs,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GetXAttrsResponseProto) Reset()                    { *m = GetXAttrsResponseProto{} }
func (m *GetXAttrsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetXAttrsResponseProto) ProtoMessage()               {}
func (*GetXAttrsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *GetXAttrsResponseProto) GetXAttrs() []*XAttrProto {
	if m != nil {
		return m.XAttrs
	}
	return nil
}

type ListXAttrsRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListXAttrsRequestProto) Reset()                    { *m = ListXAttrsRequestProto{} }
func (m *ListXAttrsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*ListXAttrsRequestProto) ProtoMessage()               {}
func (*ListXAttrsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *ListXAttrsRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type ListXAttrsResponseProto struct {
	XAttrs           []*XAttrProto `protobuf:"bytes,1,rep,name=xAttrs" json:"xAttrs,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ListXAttrsResponseProto) Reset()                    { *m = ListXAttrsResponseProto{} }
func (m *ListXAttrsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*ListXAttrsResponseProto) ProtoMessage()               {}
func (*ListXAttrsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *ListXAttrsResponseProto) GetXAttrs() []*XAttrProto {
	if m != nil {
		return m.XAttrs
	}
	return nil
}

type RemoveXAttrRequestProto struct {
	Src              *string     `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XAttr            *XAttrProto `protobuf:"bytes,2,opt,name=xAttr" json:"xAttr,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RemoveXAttrRequestProto) Reset()                    { *m = RemoveXAttrRequestProto{} }
func (m *RemoveXAttrRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveXAttrRequestProto) ProtoMessage()               {}
func (*RemoveXAttrRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *RemoveXAttrRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *RemoveXAttrRequestProto) GetXAttr() *XAttrProto {
	if m != nil {
		return m.XAttr
	}
	return nil
}

type RemoveXAttrResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveXAttrResponseProto) Reset()                    { *m = RemoveXAttrResponseProto{} }
func (m *RemoveXAttrResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RemoveXAttrResponseProto) ProtoMessage()               {}
func (*RemoveXAttrResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func init() {
	proto.RegisterType((*XAttrProto)(nil), "hadoop.hdfs.XAttrProto")
	proto.RegisterType((*XAttrEditLogProto)(nil), "hadoop.hdfs.XAttrEditLogProto")
	proto.RegisterType((*SetXAttrRequestProto)(nil), "hadoop.hdfs.SetXAttrRequestProto")
	proto.RegisterType((*SetXAttrResponseProto)(nil), "hadoop.hdfs.SetXAttrResponseProto")
	proto.RegisterType((*GetXAttrsRequestProto)(nil), "hadoop.hdfs.GetXAttrsRequestProto")
	proto.RegisterType((*GetXAttrsResponseProto)(nil), "hadoop.hdfs.GetXAttrsResponseProto")
	proto.RegisterType((*ListXAttrsRequestProto)(nil), "hadoop.hdfs.ListXAttrsRequestProto")
	proto.RegisterType((*ListXAttrsResponseProto)(nil), "hadoop.hdfs.ListXAttrsResponseProto")
	proto.RegisterType((*RemoveXAttrRequestProto)(nil), "hadoop.hdfs.RemoveXAttrRequestProto")
	proto.RegisterType((*RemoveXAttrResponseProto)(nil), "hadoop.hdfs.RemoveXAttrResponseProto")
	proto.RegisterEnum("hadoop.hdfs.XAttrSetFlagProto", XAttrSetFlagProto_name, XAttrSetFlagProto_value)
	proto.RegisterEnum("hadoop.hdfs.XAttrProto_XAttrNamespaceProto", XAttrProto_XAttrNamespaceProto_name, XAttrProto_XAttrNamespaceProto_value)
}

var fileDescriptor5 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x93, 0xcf, 0xae, 0xd2, 0x40,
	0x14, 0xc6, 0x9d, 0x96, 0xbf, 0xa7, 0x60, 0x4a, 0x15, 0xda, 0xb8, 0x22, 0x93, 0xa0, 0x44, 0x93,
	0x2e, 0xd8, 0xe8, 0xca, 0xa4, 0xe0, 0x68, 0x48, 0x00, 0xc9, 0xb4, 0x44, 0x58, 0x99, 0x06, 0x86,
	0x3f, 0x09, 0x30, 0xb5, 0x53, 0x08, 0x8f, 0xe3, 0x73, 0xf8, 0x74, 0x4e, 0x5b, 0x0c, 0xc5, 0x08,
	0xde, 0xdc, 0xdc, 0x5d, 0x33, 0xe7, 0x9c, 0xdf, 0xf7, 0x7d, 0x33, 0xa7, 0xa0, 0x9d, 0xfc, 0x28,
	0x0a, 0xed, 0x20, 0xe4, 0x11, 0x37, 0xb4, 0xb5, 0xbf, 0xe0, 0x3c, 0xb0, 0xd7, 0x8b, 0xa5, 0xc0,
	0xbf, 0x10, 0xc0, 0xd4, 0x91, 0xc5, 0x71, 0x52, 0xfb, 0x08, 0xe5, 0xbd, 0xbf, 0x63, 0x22, 0xf0,
	0xe7, 0xcc, 0x42, 0x4d, 0xa5, 0xfd, 0xbc, 0xf3, 0xce, 0xce, 0xf4, 0xdb, 0x97, 0xde, 0xf4, 0x73,
	0xf4, 0xa7, 0x3b, 0x9d, 0xaf, 0x40, 0x2e, 0x9e, 0xb7, 0x14, 0x39, 0x5a, 0x36, 0xaa, 0x90, 0x3f,
	0xfa, 0xdb, 0x03, 0xb3, 0xd4, 0x26, 0x6a, 0x57, 0xf0, 0x57, 0x78, 0xf1, 0xaf, 0x99, 0x12, 0xe4,
	0x26, 0x2e, 0xa1, 0xfa, 0x33, 0x43, 0x83, 0xa2, 0x47, 0x27, 0xae, 0x47, 0x3e, 0xe9, 0x48, 0xa2,
	0x4a, 0x2e, 0xe9, 0x4d, 0x68, 0xdf, 0x9b, 0xe9, 0x8a, 0x01, 0x50, 0x70, 0x67, 0xb2, 0x32, 0xd4,
	0x55, 0xa3, 0x08, 0x2a, 0x75, 0xbe, 0xe9, 0x39, 0xdc, 0x87, 0x5a, 0x02, 0x24, 0x8b, 0x4d, 0x34,
	0xe0, 0xab, 0x14, 0xa7, 0x81, 0x2a, 0xc2, 0xb9, 0x34, 0x8f, 0xa4, 0x83, 0x37, 0x50, 0x38, 0xc5,
	0x1d, 0x42, 0x3a, 0x52, 0xdb, 0x5a, 0xc7, 0xbc, 0x11, 0x06, 0xcf, 0xe0, 0xa5, 0xcb, 0xa2, 0xe4,
	0x80, 0xb2, 0x1f, 0x07, 0x26, 0xa2, 0xbf, 0x68, 0x71, 0x9e, 0xd7, 0x90, 0x4f, 0x68, 0x12, 0x86,
	0xee, 0xc0, 0xe2, 0x5b, 0x58, 0x6e, 0xfd, 0x55, 0x12, 0xbb, 0x8a, 0x4d, 0xa8, 0x5f, 0xd0, 0x22,
	0xe0, 0x7b, 0x91, 0x06, 0xc7, 0x43, 0xa8, 0x7f, 0x39, 0x17, 0xc4, 0x6d, 0xd1, 0x07, 0x47, 0x70,
	0xa0, 0x91, 0xc1, 0x65, 0x84, 0x32, 0x08, 0x74, 0x1f, 0xd1, 0x82, 0xc6, 0x60, 0x23, 0xfe, 0x67,
	0x09, 0x77, 0xc1, 0xcc, 0xb6, 0x3d, 0x4a, 0x6a, 0x04, 0x26, 0x65, 0x3b, 0x7e, 0x64, 0x4f, 0x73,
	0xe7, 0xf8, 0x15, 0x58, 0x57, 0xbc, 0x8c, 0xa9, 0xb7, 0x1f, 0xce, 0x7b, 0x22, 0x9f, 0xe1, 0xb3,
	0x7c, 0x97, 0x54, 0x45, 0x87, 0xca, 0xd4, 0xf1, 0x3c, 0xfa, 0xbd, 0x47, 0x89, 0xe3, 0x11, 0xb9,
	0x71, 0x35, 0xa8, 0xa6, 0x27, 0x94, 0x8c, 0x07, 0x4e, 0x8f, 0xe8, 0x4a, 0xf7, 0x3d, 0xb4, 0x78,
	0xb8, 0xb2, 0x7d, 0xb9, 0xad, 0x6b, 0x76, 0x25, 0x9d, 0xfc, 0x4b, 0x73, 0xbe, 0x4d, 0x3f, 0xba,
	0xda, 0xc5, 0x8a, 0xf8, 0x89, 0xd0, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0xfb, 0x21, 0x58,
	0x72, 0x03, 0x00, 0x00,
}
