// Code generated by protoc-gen-go.
// source: ProtobufRpcEngine.proto
// DO NOT EDIT!

package hadoop_common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
// This message is the header for the Protobuf Rpc Engine
// when sending a RPC request from  RPC client to the RPC server.
// The actual request (serialized as protobuf) follows this request.
//
// No special header is needed for the Rpc Response for Protobuf Rpc Engine.
// The normal RPC response header (see RpcHeader.proto) are sufficient.
type RequestHeaderProto struct {
	// * Name of the RPC method
	MethodName *string `protobuf:"bytes,1,req,name=methodName" json:"methodName,omitempty"`
	// *
	// RPCs for a particular interface (ie protocol) are done using a
	// IPC connection that is setup using rpcProxy.
	// The rpcProxy's has a declared protocol name that is
	// sent form client to server at connection time.
	//
	// Each Rpc call also sends a protocol name
	// (called declaringClassprotocolName). This name is usually the same
	// as the connection protocol name except in some cases.
	// For example metaProtocols such ProtocolInfoProto which get metainfo
	// about the protocol reuse the connection but need to indicate that
	// the actual protocol is different (i.e. the protocol is
	// ProtocolInfoProto) since they reuse the connection; in this case
	// the declaringClassProtocolName field is set to the ProtocolInfoProto
	DeclaringClassProtocolName *string `protobuf:"bytes,2,req,name=declaringClassProtocolName" json:"declaringClassProtocolName,omitempty"`
	// * protocol version of class declaring the called method
	ClientProtocolVersion *uint64 `protobuf:"varint,3,req,name=clientProtocolVersion" json:"clientProtocolVersion,omitempty"`
	XXX_unrecognized      []byte  `json:"-"`
}

func (m *RequestHeaderProto) Reset()                    { *m = RequestHeaderProto{} }
func (m *RequestHeaderProto) String() string            { return proto.CompactTextString(m) }
func (*RequestHeaderProto) ProtoMessage()               {}
func (*RequestHeaderProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RequestHeaderProto) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

func (m *RequestHeaderProto) GetDeclaringClassProtocolName() string {
	if m != nil && m.DeclaringClassProtocolName != nil {
		return *m.DeclaringClassProtocolName
	}
	return ""
}

func (m *RequestHeaderProto) GetClientProtocolVersion() uint64 {
	if m != nil && m.ClientProtocolVersion != nil {
		return *m.ClientProtocolVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeaderProto)(nil), "hadoop.common.RequestHeaderProto")
}

var fileDescriptor1 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x8e, 0xb1, 0xca, 0xc2, 0x30,
	0x14, 0x46, 0x69, 0xff, 0x7f, 0x31, 0xe0, 0x12, 0x10, 0x8b, 0xa0, 0x48, 0x27, 0xa7, 0x3c, 0x81,
	0x53, 0x45, 0x70, 0x12, 0xe9, 0xe0, 0x1e, 0x6f, 0xae, 0x6d, 0x30, 0xc9, 0x8d, 0x49, 0xfa, 0x3e,
	0x3e, 0xaa, 0x35, 0xea, 0xe4, 0xfa, 0x9d, 0xf3, 0xc1, 0x61, 0xf3, 0x53, 0xa0, 0x44, 0x97, 0xe1,
	0xda, 0x7a, 0xd8, 0xbb, 0x4e, 0x3b, 0x14, 0xfe, 0xb5, 0xf0, 0x69, 0x2f, 0x15, 0x91, 0x17, 0x40,
	0xd6, 0x92, 0xab, 0x6f, 0x8c, 0xb7, 0x78, 0x1f, 0x30, 0xa6, 0x03, 0x4a, 0x85, 0x21, 0xdf, 0x38,
	0x67, 0xcc, 0x62, 0xea, 0x49, 0x1d, 0xa5, 0xc5, 0xaa, 0x58, 0x97, 0x9b, 0x09, 0xaf, 0xd9, 0x42,
	0x21, 0x18, 0x19, 0xb4, 0xeb, 0x76, 0x46, 0xc6, 0x98, 0x55, 0x20, 0x93, 0x9d, 0x32, 0x3b, 0x4b,
	0x36, 0x03, 0xa3, 0xd1, 0xa5, 0x2f, 0x3b, 0x63, 0x88, 0x9a, 0x5c, 0xf5, 0x37, 0xe2, 0xff, 0x66,
	0xcb, 0x56, 0x14, 0x3a, 0x21, 0xbd, 0x84, 0x1e, 0xc5, 0x27, 0x44, 0x7b, 0x78, 0xa7, 0x8d, 0xb1,
	0xcd, 0x6f, 0x76, 0x1e, 0xe2, 0xa3, 0x28, 0x9e, 0x01, 0x00, 0x00, 0xff, 0xff, 0x03, 0x34, 0x85,
	0x03, 0xd3, 0x00, 0x00, 0x00,
}
