// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ReconfigurationProtocol.proto

package hadoop_hdfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// * Asks NN/DN to reload configuration file.
type StartReconfigurationRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReconfigurationRequestProto) Reset()         { *m = StartReconfigurationRequestProto{} }
func (m *StartReconfigurationRequestProto) String() string { return proto.CompactTextString(m) }
func (*StartReconfigurationRequestProto) ProtoMessage()    {}
func (*StartReconfigurationRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d, []int{0}
}
func (m *StartReconfigurationRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReconfigurationRequestProto.Unmarshal(m, b)
}
func (m *StartReconfigurationRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReconfigurationRequestProto.Marshal(b, m, deterministic)
}
func (dst *StartReconfigurationRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReconfigurationRequestProto.Merge(dst, src)
}
func (m *StartReconfigurationRequestProto) XXX_Size() int {
	return xxx_messageInfo_StartReconfigurationRequestProto.Size(m)
}
func (m *StartReconfigurationRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReconfigurationRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_StartReconfigurationRequestProto proto.InternalMessageInfo

type StartReconfigurationResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReconfigurationResponseProto) Reset()         { *m = StartReconfigurationResponseProto{} }
func (m *StartReconfigurationResponseProto) String() string { return proto.CompactTextString(m) }
func (*StartReconfigurationResponseProto) ProtoMessage()    {}
func (*StartReconfigurationResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d, []int{1}
}
func (m *StartReconfigurationResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReconfigurationResponseProto.Unmarshal(m, b)
}
func (m *StartReconfigurationResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReconfigurationResponseProto.Marshal(b, m, deterministic)
}
func (dst *StartReconfigurationResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReconfigurationResponseProto.Merge(dst, src)
}
func (m *StartReconfigurationResponseProto) XXX_Size() int {
	return xxx_messageInfo_StartReconfigurationResponseProto.Size(m)
}
func (m *StartReconfigurationResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReconfigurationResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_StartReconfigurationResponseProto proto.InternalMessageInfo

// * Query the running status of reconfiguration process
type GetReconfigurationStatusRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReconfigurationStatusRequestProto) Reset()         { *m = GetReconfigurationStatusRequestProto{} }
func (m *GetReconfigurationStatusRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetReconfigurationStatusRequestProto) ProtoMessage()    {}
func (*GetReconfigurationStatusRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d, []int{2}
}
func (m *GetReconfigurationStatusRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReconfigurationStatusRequestProto.Unmarshal(m, b)
}
func (m *GetReconfigurationStatusRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReconfigurationStatusRequestProto.Marshal(b, m, deterministic)
}
func (dst *GetReconfigurationStatusRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReconfigurationStatusRequestProto.Merge(dst, src)
}
func (m *GetReconfigurationStatusRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetReconfigurationStatusRequestProto.Size(m)
}
func (m *GetReconfigurationStatusRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReconfigurationStatusRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetReconfigurationStatusRequestProto proto.InternalMessageInfo

type GetReconfigurationStatusConfigChangeProto struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	OldValue             *string  `protobuf:"bytes,2,req,name=oldValue" json:"oldValue,omitempty"`
	NewValue             *string  `protobuf:"bytes,3,opt,name=newValue" json:"newValue,omitempty"`
	ErrorMessage         *string  `protobuf:"bytes,4,opt,name=errorMessage" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReconfigurationStatusConfigChangeProto) Reset() {
	*m = GetReconfigurationStatusConfigChangeProto{}
}
func (m *GetReconfigurationStatusConfigChangeProto) String() string {
	return proto.CompactTextString(m)
}
func (*GetReconfigurationStatusConfigChangeProto) ProtoMessage() {}
func (*GetReconfigurationStatusConfigChangeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d, []int{3}
}
func (m *GetReconfigurationStatusConfigChangeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReconfigurationStatusConfigChangeProto.Unmarshal(m, b)
}
func (m *GetReconfigurationStatusConfigChangeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReconfigurationStatusConfigChangeProto.Marshal(b, m, deterministic)
}
func (dst *GetReconfigurationStatusConfigChangeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReconfigurationStatusConfigChangeProto.Merge(dst, src)
}
func (m *GetReconfigurationStatusConfigChangeProto) XXX_Size() int {
	return xxx_messageInfo_GetReconfigurationStatusConfigChangeProto.Size(m)
}
func (m *GetReconfigurationStatusConfigChangeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReconfigurationStatusConfigChangeProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetReconfigurationStatusConfigChangeProto proto.InternalMessageInfo

func (m *GetReconfigurationStatusConfigChangeProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GetReconfigurationStatusConfigChangeProto) GetOldValue() string {
	if m != nil && m.OldValue != nil {
		return *m.OldValue
	}
	return ""
}

func (m *GetReconfigurationStatusConfigChangeProto) GetNewValue() string {
	if m != nil && m.NewValue != nil {
		return *m.NewValue
	}
	return ""
}

func (m *GetReconfigurationStatusConfigChangeProto) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type GetReconfigurationStatusResponseProto struct {
	StartTime            *int64                                       `protobuf:"varint,1,req,name=startTime" json:"startTime,omitempty"`
	EndTime              *int64                                       `protobuf:"varint,2,opt,name=endTime" json:"endTime,omitempty"`
	Changes              []*GetReconfigurationStatusConfigChangeProto `protobuf:"bytes,3,rep,name=changes" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *GetReconfigurationStatusResponseProto) Reset()         { *m = GetReconfigurationStatusResponseProto{} }
func (m *GetReconfigurationStatusResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetReconfigurationStatusResponseProto) ProtoMessage()    {}
func (*GetReconfigurationStatusResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d, []int{4}
}
func (m *GetReconfigurationStatusResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReconfigurationStatusResponseProto.Unmarshal(m, b)
}
func (m *GetReconfigurationStatusResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReconfigurationStatusResponseProto.Marshal(b, m, deterministic)
}
func (dst *GetReconfigurationStatusResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReconfigurationStatusResponseProto.Merge(dst, src)
}
func (m *GetReconfigurationStatusResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetReconfigurationStatusResponseProto.Size(m)
}
func (m *GetReconfigurationStatusResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReconfigurationStatusResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetReconfigurationStatusResponseProto proto.InternalMessageInfo

func (m *GetReconfigurationStatusResponseProto) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *GetReconfigurationStatusResponseProto) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *GetReconfigurationStatusResponseProto) GetChanges() []*GetReconfigurationStatusConfigChangeProto {
	if m != nil {
		return m.Changes
	}
	return nil
}

// * Query the reconfigurable properties on NN/DN.
type ListReconfigurablePropertiesRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReconfigurablePropertiesRequestProto) Reset() {
	*m = ListReconfigurablePropertiesRequestProto{}
}
func (m *ListReconfigurablePropertiesRequestProto) String() string { return proto.CompactTextString(m) }
func (*ListReconfigurablePropertiesRequestProto) ProtoMessage()    {}
func (*ListReconfigurablePropertiesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d, []int{5}
}
func (m *ListReconfigurablePropertiesRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReconfigurablePropertiesRequestProto.Unmarshal(m, b)
}
func (m *ListReconfigurablePropertiesRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReconfigurablePropertiesRequestProto.Marshal(b, m, deterministic)
}
func (dst *ListReconfigurablePropertiesRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReconfigurablePropertiesRequestProto.Merge(dst, src)
}
func (m *ListReconfigurablePropertiesRequestProto) XXX_Size() int {
	return xxx_messageInfo_ListReconfigurablePropertiesRequestProto.Size(m)
}
func (m *ListReconfigurablePropertiesRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReconfigurablePropertiesRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListReconfigurablePropertiesRequestProto proto.InternalMessageInfo

type ListReconfigurablePropertiesResponseProto struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReconfigurablePropertiesResponseProto) Reset() {
	*m = ListReconfigurablePropertiesResponseProto{}
}
func (m *ListReconfigurablePropertiesResponseProto) String() string {
	return proto.CompactTextString(m)
}
func (*ListReconfigurablePropertiesResponseProto) ProtoMessage() {}
func (*ListReconfigurablePropertiesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d, []int{6}
}
func (m *ListReconfigurablePropertiesResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReconfigurablePropertiesResponseProto.Unmarshal(m, b)
}
func (m *ListReconfigurablePropertiesResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReconfigurablePropertiesResponseProto.Marshal(b, m, deterministic)
}
func (dst *ListReconfigurablePropertiesResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReconfigurablePropertiesResponseProto.Merge(dst, src)
}
func (m *ListReconfigurablePropertiesResponseProto) XXX_Size() int {
	return xxx_messageInfo_ListReconfigurablePropertiesResponseProto.Size(m)
}
func (m *ListReconfigurablePropertiesResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReconfigurablePropertiesResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListReconfigurablePropertiesResponseProto proto.InternalMessageInfo

func (m *ListReconfigurablePropertiesResponseProto) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*StartReconfigurationRequestProto)(nil), "hadoop.hdfs.StartReconfigurationRequestProto")
	proto.RegisterType((*StartReconfigurationResponseProto)(nil), "hadoop.hdfs.StartReconfigurationResponseProto")
	proto.RegisterType((*GetReconfigurationStatusRequestProto)(nil), "hadoop.hdfs.GetReconfigurationStatusRequestProto")
	proto.RegisterType((*GetReconfigurationStatusConfigChangeProto)(nil), "hadoop.hdfs.GetReconfigurationStatusConfigChangeProto")
	proto.RegisterType((*GetReconfigurationStatusResponseProto)(nil), "hadoop.hdfs.GetReconfigurationStatusResponseProto")
	proto.RegisterType((*ListReconfigurablePropertiesRequestProto)(nil), "hadoop.hdfs.ListReconfigurablePropertiesRequestProto")
	proto.RegisterType((*ListReconfigurablePropertiesResponseProto)(nil), "hadoop.hdfs.ListReconfigurablePropertiesResponseProto")
}

func init() {
	proto.RegisterFile("ReconfigurationProtocol.proto", fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d)
}

var fileDescriptor_ReconfigurationProtocol_fb5dbccf61ba722d = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xb1, 0x8e, 0xd3, 0x40,
	0x10, 0xd5, 0xc6, 0x91, 0x42, 0x26, 0x54, 0x2b, 0x0a, 0xcb, 0x0a, 0xc8, 0x18, 0x82, 0x1c, 0x24,
	0x2c, 0x11, 0x89, 0xb4, 0x48, 0x49, 0x41, 0x13, 0xa4, 0xc8, 0x41, 0xf4, 0x8b, 0x3d, 0xb1, 0x2d,
	0x19, 0xaf, 0xd9, 0x5d, 0x43, 0x4d, 0x47, 0xc3, 0x17, 0x5c, 0x73, 0xfd, 0x55, 0xf7, 0x87, 0x27,
	0x6f, 0xce, 0x97, 0x75, 0x14, 0xe7, 0x7c, 0x95, 0x77, 0x66, 0xde, 0x3c, 0xcf, 0x7b, 0x3b, 0x5a,
	0x78, 0x19, 0x62, 0xc4, 0x8b, 0x7d, 0x96, 0x54, 0x82, 0xa9, 0x8c, 0x17, 0x5b, 0xc1, 0x15, 0x8f,
	0x78, 0x1e, 0x94, 0xf5, 0x81, 0x4e, 0x52, 0x16, 0x73, 0x5e, 0x06, 0x69, 0xbc, 0x97, 0x9e, 0x07,
	0xee, 0x4e, 0x31, 0xa1, 0x4e, 0x5a, 0x42, 0xfc, 0x55, 0xa1, 0x54, 0xba, 0xd3, 0x7b, 0x03, 0xaf,
	0xcf, 0x63, 0x64, 0xc9, 0x0b, 0x89, 0x07, 0xd0, 0x3b, 0x78, 0xfb, 0x05, 0x4f, 0x21, 0x3b, 0xc5,
	0x54, 0x25, 0x5b, 0x64, 0x57, 0x04, 0xe6, 0x5d, 0xc0, 0xb5, 0x4e, 0xad, 0x53, 0x56, 0x24, 0x07,
	0x56, 0x4a, 0x61, 0x58, 0xb0, 0x9f, 0x68, 0x13, 0x77, 0xe0, 0x8f, 0x43, 0x7d, 0xa6, 0x0e, 0x3c,
	0xe3, 0x79, 0xfc, 0x9d, 0xe5, 0x15, 0xda, 0x03, 0x9d, 0x7f, 0x88, 0xeb, 0x5a, 0x81, 0x7f, 0x0e,
	0x35, 0xcb, 0x25, 0x75, 0xad, 0x89, 0xa9, 0x07, 0xcf, 0x51, 0x08, 0x2e, 0xbe, 0xa2, 0x94, 0x2c,
	0x41, 0x7b, 0xa8, 0xeb, 0xad, 0x9c, 0x77, 0x4b, 0x60, 0xd6, 0x2d, 0xc3, 0xd0, 0x4b, 0xa7, 0x30,
	0x96, 0xb5, 0x29, 0xdf, 0xb2, 0xfb, 0xf1, 0xac, 0xf0, 0x98, 0xa0, 0x36, 0x8c, 0xb0, 0x88, 0x75,
	0x6d, 0xe0, 0x12, 0xdf, 0x0a, 0x9b, 0x90, 0x6e, 0x61, 0x14, 0x69, 0x81, 0xd2, 0xb6, 0x5c, 0xcb,
	0x9f, 0x2c, 0x96, 0x81, 0x71, 0x1f, 0x41, 0x6f, 0x6b, 0xc2, 0x86, 0xc6, 0x7b, 0x0f, 0xfe, 0x26,
	0x93, 0x66, 0xdb, 0x8f, 0xbc, 0xc6, 0x94, 0x28, 0x54, 0x86, 0x6d, 0xf7, 0x3f, 0xc3, 0xfc, 0x32,
	0xd6, 0x94, 0x78, 0x34, 0xdf, 0x6a, 0xcc, 0x5f, 0xdc, 0x58, 0xf0, 0xaa, 0x63, 0xbd, 0x76, 0x28,
	0x7e, 0x67, 0x11, 0xd2, 0xbf, 0x04, 0xec, 0xa4, 0x43, 0x06, 0xfd, 0xd8, 0x4b, 0xad, 0x39, 0xb3,
	0xb3, 0xe8, 0xd9, 0x62, 0x8e, 0x5e, 0xc1, 0x0b, 0x79, 0x66, 0x65, 0xe9, 0x87, 0x16, 0xd7, 0x63,
	0x9b, 0xef, 0x04, 0x3d, 0xe0, 0xe6, 0x6f, 0xff, 0x13, 0x98, 0xe6, 0x17, 0xfc, 0xa5, 0x9f, 0x5a,
	0x84, 0x7d, 0xaf, 0xcd, 0x59, 0x3e, 0xa1, 0xcd, 0x98, 0x67, 0xb5, 0x81, 0x19, 0x17, 0x49, 0xc0,
	0x4a, 0x16, 0xa5, 0xd8, 0xe2, 0x28, 0x5b, 0x6f, 0xc2, 0xaa, 0xeb, 0xc9, 0xd0, 0x5f, 0xf9, 0x8f,
	0x90, 0x6b, 0x42, 0xee, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0x3f, 0x1a, 0x33, 0x58, 0x04, 0x00,
	0x00,
}
